#!/usr/bin/env node
// pi-acp: SPIKE shim speaking the ACP subset quack uses (internal/acp) on
// stdio, driving `pi --mode rpc` as the actual coding agent underneath.
import { spawn } from "node:child_process";
import { createInterface } from "node:readline";
import { mkdtempSync, writeFileSync, mkdirSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { McpClient } from "./mcp-client.mjs";

const here = dirname(fileURLToPath(import.meta.url));

// Model/endpoint/skills come from OPENCODE_CONFIG_CONTENT, the env quack
// already generates for every ACP agent (serve.go opencodeEnv) - zero Go changes.
const ocCfg = process.env.OPENCODE_CONFIG_CONTENT
  ? JSON.parse(process.env.OPENCODE_CONFIG_CONTENT)
  : {};
const prov = (() => {
  const p = ocCfg.provider?.quack;
  if (!p) return null;
  return { baseUrl: p.options.baseURL, apiKey: p.options.apiKey || "unused", model: Object.keys(p.models)[0] };
})();

// pi config dir (models.json, settings.json, extensions/) - fresh per run.
const piDir = mkdtempSync(join(tmpdir(), "pi-acp-"));
if (prov) {
  writeFileSync(join(piDir, "models.json"), JSON.stringify({
    providers: {
      quack: {
        baseUrl: prov.baseUrl,
        api: "openai-completions",
        apiKey: prov.apiKey,
        compat: { supportsDeveloperRole: false, supportsReasoningEffort: false },
        models: [{ id: prov.model }],
      },
    },
  }));
}
// Skills: same roots opencode gets via skills.paths (serve.go acpSkillPaths).
if (ocCfg.skills?.paths?.length)
  writeFileSync(join(piDir, "settings.json"), JSON.stringify({ skills: ocCfg.skills.paths }));

// The MCP bridge: quack hands its loopback server in session/new mcpServers
// (memorymcp.go memoryMCPServers, gated on our advertised http/sse caps).
// The shim does the handshake + tools/list, then generates a pi extension
// that registers each tool as quackmcp_<name> and proxies calls over HTTP.
async function bridgeMcp(servers) {
  const s = servers?.[0];
  const url = s?.url ?? s?.sse?.url ?? s?.http?.url;
  if (!url) return;
  const name = s.name ?? s.sse?.name ?? "quackmcp";
  const client = new McpClient(url);
  await client.connect();
  const { tools } = await client.toolsList();
  const extDir = join(piDir, "extensions");
  mkdirSync(extDir, { recursive: true });
  writeFileSync(join(extDir, "quackmcp.json"), JSON.stringify({ url, prefix: name, tools }));
  writeFileSync(join(extDir, "quackmcp.ts"), `// generated by pi-acp.mjs: proxies quack's loopback MCP tools into pi
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { McpClient } from "${pathToFileURL(join(here, "mcp-client.mjs")).href}";

export default function (pi: any) {
  const cfg = JSON.parse(readFileSync(join(dirname(fileURLToPath(import.meta.url)), "quackmcp.json"), "utf8"));
  const client = new McpClient(cfg.url);
  let ready: Promise<void> | null = null;
  for (const t of cfg.tools) {
    pi.registerTool({
      name: cfg.prefix + "_" + t.name,
      label: t.name,
      description: t.description || t.name,
      parameters: t.inputSchema,
      async execute(_id: string, params: any) {
        await (ready ??= client.connect());
        const r = await client.toolsCall(t.name, params);
        return { content: r.content ?? [{ type: "text", text: JSON.stringify(r) }], isError: !!r.isError, details: {} };
      },
    });
  }
}
`);
}

const KIND = {
  bash: "execute", read: "read", edit: "edit", write: "edit",
  grep: "search", find: "search", ls: "search", fetch: "fetch",
};

const out = (obj) => process.stdout.write(JSON.stringify(obj) + "\n");

let pi = null;            // child process
let sessionId = null;
let promptReq = null;     // pending session/prompt JSON-RPC id
let cancelled = false;

function notify(update) {
  out({ jsonrpc: "2.0", method: "session/update", params: { sessionId, update } });
}

function textOf(content) {
  return (content || []).filter((c) => c.type === "text").map((c) => c.text).join("");
}

function onPiEvent(ev) {
  switch (ev.type) {
    case "message_update": {
      const e = ev.assistantMessageEvent || {};
      if (e.type === "text_delta")
        notify({ sessionUpdate: "agent_message_chunk", content: { type: "text", text: e.delta } });
      else if (e.type === "thinking_delta")
        notify({ sessionUpdate: "agent_thought_chunk", content: { type: "text", text: e.delta } });
      if (ev.usage?.totalTokens)
        notify({ sessionUpdate: "usage_update", used: ev.usage.totalTokens, size: 0 });
      break;
    }
    case "tool_execution_start":
      notify({
        sessionUpdate: "tool_call", toolCallId: ev.toolCallId,
        title: ev.toolName, kind: KIND[ev.toolName] || "other",
        status: "in_progress", rawInput: ev.args || {},
      });
      break;
    case "tool_execution_end": {
      const txt = textOf(ev.result?.content);
      notify({
        sessionUpdate: "tool_call_update", toolCallId: ev.toolCallId,
        status: ev.isError ? "failed" : "completed",
        rawOutput: { output: txt },
        content: txt ? [{ type: "content", content: { type: "text", text: txt } }] : [],
      });
      break;
    }
    case "agent_settled":
      if (promptReq !== null) {
        out({ jsonrpc: "2.0", id: promptReq, result: { stopReason: cancelled ? "cancelled" : "end_turn" } });
        promptReq = null;
        cancelled = false;
      }
      break;
  }
}

function startPi(cwd) {
  const cmd = process.env.PI_ACP_PI_CMD || "pi";
  const args = process.env.PI_ACP_PI_CMD
    ? []
    : ["--mode", "rpc", "--no-session", "--provider", "quack", "--model", prov.model];
  pi = spawn(cmd, args, { cwd, env: { ...process.env, PI_CODING_AGENT_DIR: piDir }, stdio: ["pipe", "pipe", "inherit"] });
  pi.on("exit", (code) => {
    if (promptReq !== null)
      out({ jsonrpc: "2.0", id: promptReq, error: { code: -32000, message: `pi exited (${code})` } });
    process.exit(code ?? 1);
  });
  createInterface({ input: pi.stdout }).on("line", (l) => {
    if (!l.trim()) return;
    try { onPiEvent(JSON.parse(l)); } catch { /* non-JSON noise */ }
  });
}

async function handle(msg) {
  const reply = (result) => out({ jsonrpc: "2.0", id: msg.id, result });
  const fail = (message) => out({ jsonrpc: "2.0", id: msg.id, error: { code: -32000, message } });
  switch (msg.method) {
    case "initialize":
      reply({
        protocolVersion: 1,
        agentCapabilities: {
          loadSession: false,
          mcpCapabilities: { http: true, sse: true, acp: false },
          promptCapabilities: { audio: false, embeddedContext: false, image: false },
        },
        authMethods: [],
      });
      break;
    case "session/new":
      try {
        await bridgeMcp(msg.params.mcpServers);
      } catch (e) {
        return fail(`mcp bridge: ${e.message}`);
      }
      sessionId = "pi-" + Math.random().toString(36).slice(2);
      startPi(msg.params.cwd);
      reply({ sessionId });
      break;
    case "session/prompt": {
      promptReq = msg.id;
      const text = (msg.params.prompt || []).map((b) => b.text || "").join("");
      pi.stdin.write(JSON.stringify({ type: "prompt", message: text }) + "\n");
      break;
    }
    case "session/cancel":
      cancelled = true;
      pi?.stdin.write(JSON.stringify({ type: "abort" }) + "\n");
      break;
    default:
      if (msg.id !== undefined)
        out({ jsonrpc: "2.0", id: msg.id, error: { code: -32601, message: `method not found: ${msg.method}` } });
  }
}

createInterface({ input: process.stdin }).on("line", (l) => {
  if (!l.trim()) return;
  handle(JSON.parse(l));
});
process.stdin.on("end", () => { pi?.kill("SIGKILL"); process.exit(0); });
