package cli

import (
	"fmt"
	"strings"
)

// InitAnswers is the collected wizard output for `quack server init` (and the
// local branch of `quack init`). The wizard (internal/wizard) populates this;
// EmitServerConfig turns it into a quack.yaml. Kept here, not in the wizard
// package, so it's testable without constructing a Huh form.
type InitAnswers struct {
	Endpoint string // LLM endpoint (OpenAI-compatible base URL)
	APIKey   string // typed; emitted as ${LLM_API_KEY} (the export is printed)

	MainModel   string // orchestrator + researcher (the common case)
	JudgeModel  string // blank ⇒ trust gate disabled
	EmbedModel  string // blank ⇒ semantic memory disabled
	VisionModel string // blank ⇒ no image-reader agent
	AudioModel  string // blank ⇒ no media-reader agent

	// Stores — each kind picks the adapter; url is the connection (blank ⇒ the
	// emitter fills the no-docker default for that kind).
	SessionKind string // sqlite | postgres
	SessionURL  string
	MemoryKind  string // sqlite | qdrant  (blank when EmbedModel empty)
	MemoryURL   string
	SearchKind  string // exa | searxng   (blank when web search off)
	SearchURL   string
	FetchKind   string // direct | crawl4ai (blank when web fetch off)
	FetchURL    string

	WebSearch bool // optional-feature toggles (drive which stores are emitted)
	WebFetch  bool
}

// EmitServerConfig renders a complete quack.yaml from the answers. Secrets
// (API key, any DB password in a URL) are emitted as ${ENV} references and the
// caller prints the matching export commands. Non-secrets (endpoint, model
// names) are hardcoded — the wizard output works with no env setup beyond the
// one secret. The agent roster is tailored: media-reader only with an audio
// model, image-reader only with a vision model.
func EmitServerConfig(a InitAnswers) string {
	var b strings.Builder
	b.WriteString("# Quack configuration — generated by `quack server init`.\n")
	b.WriteString("# The API key is read from ${LLM_API_KEY}; set it with the export the wizard prints.\n\n")

	b.WriteString("providers:\n  default:\n    kind: openai\n")
	fmt.Fprintf(&b, "    endpoint: %s\n    api_key: ${LLM_API_KEY}\n\n", a.Endpoint)

	b.WriteString("stores:\n")
	emitStore(&b, "default_postgres", a.SessionKind, a.SessionURL, defaultStoreURL(a.SessionKind, "session"))
	if a.EmbedModel != "" {
		emitStore(&b, "default_vector", a.MemoryKind, a.MemoryURL, defaultStoreURL(a.MemoryKind, "memory"))
	}
	b.WriteString("\n")

	b.WriteString("session:\n  store: default_postgres\n")
	if a.EmbedModel == "" {
		b.WriteString("  # semantic memory is off (no embedding model was selected)\n")
	}
	b.WriteString("\n")

	fmt.Fprintf(&b, "orchestrator:\n  provider: default\n  model: %s\n", a.MainModel)
	emitOrchTools(&b, a)
	b.WriteString("\n")

	b.WriteString("agents:\n")
	researcherTools := "[web_search, web_fetch, summarize, current_date"
	if a.EmbedModel != "" {
		researcherTools += ", stage_memory"
	}
	researcherTools += "]"
	emitAgent(&b, "web-researcher", a.MainModel, 65536, researcherTools, a)
	emitAgent(&b, "synthesizer", a.MainModel, 65536, "[]", a)
	if a.AudioModel != "" {
		emitAgent(&b, "media-reader", a.AudioModel, 32768, "[]", a)
		b.WriteString("    inputs: [text, image, audio]\n")
	}
	if a.VisionModel != "" {
		emitAgent(&b, "image-reader", a.VisionModel, 32768, "[]", a)
		b.WriteString("    inputs: [text, image]\n")
	}
	b.WriteString("\n")

	b.WriteString("tools:\n")
	if a.WebSearch {
		emitTool(&b, "web_search", a.SearchKind, a.SearchURL)
	}
	if a.WebFetch {
		emitTool(&b, "web_fetch", a.FetchKind, a.FetchURL)
	}
	if a.EmbedModel != "" {
		b.WriteString("  stage_memory:\n    store: default_vector\n")
	}
	b.WriteString("\n")

	if a.JudgeModel != "" {
		b.WriteString("gates:\n  enabled: true\n  deterministic_rounds: 1\n  self_critique_rounds: 1\n")
		fmt.Fprintf(&b, "  judge:\n    provider: default\n    model: %s\n    rounds: 1\n    threshold: 0.6\n\n", a.JudgeModel)
	}

	b.WriteString("dag:\n  max_active_nodes: 2\n\n")
	b.WriteString("server:\n  addr: \":8080\"\n")
	return b.String()
}

// EnvExports is the set of `export` lines the wizard prints so the emitted
// ${ENV} references resolve. Only secrets get env refs (the API key); the
// endpoint and model names are hardcoded into the config, so there's nothing
// to export beyond the key.
func EnvExports(a InitAnswers) []string {
	var out []string
	if a.APIKey != "" {
		out = append(out, fmt.Sprintf("export LLM_API_KEY=%q", a.APIKey))
	}
	return out
}

func emitStore(b *strings.Builder, name, kind, url, fallback string) {
	if kind == "" {
		kind = "sqlite"
	}
	if url == "" {
		url = fallback
	}
	fmt.Fprintf(b, "  %s:\n    kind: %s\n    url: %s\n", name, kind, url)
}

func emitTool(b *strings.Builder, name, kind, url string) {
	if kind == "" {
		return
	}
	if url == "" {
		fmt.Fprintf(b, "  %s:\n    kind: %s\n", name, kind)
		return
	}
	fmt.Fprintf(b, "  %s:\n    kind: %s\n    url: %s\n", name, kind, url)
}

func emitOrchTools(b *strings.Builder, a InitAnswers) {
	tools := []string{"web_search", "web_fetch", "summarize", "current_date"}
	if a.EmbedModel != "" {
		tools = append(tools, "commit_memory")
	}
	fmt.Fprintf(b, "  tools: [%s]\n", strings.Join(tools, ", "))
}

func emitAgent(b *strings.Builder, name, model string, ctx int, tools string, _ InitAnswers) {
	fmt.Fprintf(b, "  %s:\n    bundle: agents/%s\n    provider: default\n    model: %s\n    context_window: %d\n    tools: %s\n",
		name, name, model, ctx, tools)
}

// defaultStoreURL is the no-docker default connection for a kind (used when the
// user accepts the default). sqlite → a file path; qdrant → localhost; postgres
// → localhost with the quack/quack creds the managed stack uses.
func defaultStoreURL(kind, role string) string {
	switch kind {
	case "sqlite":
		return "quack.db"
	case "qdrant":
		return "localhost:6334"
	case "postgres":
		return "postgres://quack:quack@localhost:5432/quack?sslmode=disable"
	default:
		return ""
	}
}
