package cli

import (
	"fmt"
	"strings"
)

// InitAnswers is the collected wizard output for `quack server init` (and the
// local branch of `quack init`). The wizard (internal/wizard) populates this;
// EmitServerConfig turns it into a quack.yaml. Kept here, not in the wizard
// package, so it's testable without constructing a Huh form.
type InitAnswers struct {
	Endpoint string // LLM endpoint (OpenAI-compatible base URL)
	APIKey   string // typed; emitted as ${QUACK_LLM_API_KEY} (the export is printed)

	MainModel   string // orchestrator + researcher (the common case)
	JudgeModel  string // blank ⇒ trust gate disabled
	EmbedModel  string // blank ⇒ semantic memory disabled
	VisionModel string // blank ⇒ no image-reader agent
	AudioModel  string // blank ⇒ no media-reader agent

	// Stores - each kind picks the adapter; url is the connection (blank ⇒ the
	// emitter fills the no-docker default for that kind).
	SessionKind string // sqlite | postgres
	SessionURL  string
	MemoryKind  string // sqlite | qdrant  (blank when EmbedModel empty)
	MemoryURL   string
	SearchKind  string // exa | searxng   (blank when web search off)
	SearchURL   string
	FetchKind   string // direct | crawl4ai (blank when web fetch off)
	FetchURL    string

	WebSearch bool // optional-feature toggles (drive which stores are emitted)
	WebFetch  bool

	// Coding - emit the coding agents (code-implementer/explorer/reviewer) plus
	// the workspace section they need (sandbox + run_command/run_code guards).
	Coding     bool
	CoderModel string // blank ⇒ reuse MainModel
	Sandbox    string // workspace.sandbox: bwrap | none (blank ⇒ bwrap, the server default)
}

// EmitServerConfig renders a complete quack.yaml from the answers. Secrets
// (API key, any DB password in a URL) are emitted as ${ENV} references and the
// caller prints the matching export commands. Non-secrets (endpoint, model
// names) are hardcoded - the wizard output works with no env setup beyond the
// one secret. The agent roster is tailored: media-reader only with an audio
// model, image-reader only with a vision model.
func EmitServerConfig(a InitAnswers) string {
	var b strings.Builder
	b.WriteString("# Quack configuration - generated by `quack server init`.\n")
	b.WriteString("# The API key is read from ${QUACK_LLM_API_KEY}; set it with the export the wizard prints.\n\n")

	b.WriteString("providers:\n  default:\n    kind: openai\n")
	fmt.Fprintf(&b, "    endpoint: %s\n    api_key: ${QUACK_LLM_API_KEY}\n\n", a.Endpoint)

	b.WriteString("stores:\n")
	emitStore(&b, "default_postgres", a.SessionKind, a.SessionURL)
	if a.EmbedModel != "" {
		emitStore(&b, "default_vector", a.MemoryKind, a.MemoryURL)
	}
	b.WriteString("\n")

	b.WriteString("session:\n  store: default_postgres\n")
	if a.EmbedModel == "" {
		b.WriteString("  # semantic memory is off (no embedding model was selected)\n")
	}
	b.WriteString("\n")

	fmt.Fprintf(&b, "orchestrator:\n  provider: default\n  model: %s\n", a.MainModel)
	emitOrchTools(&b, a)
	b.WriteString("\n")

	emitModels(&b, a)

	b.WriteString("agents:\n")
	researcherTools := "[web_search, web_fetch, summarize, current_date"
	if a.EmbedModel != "" {
		researcherTools += ", stage_memory"
	}
	researcherTools += "]"
	emitAgent(&b, "web-researcher", a.MainModel, 65536, researcherTools)
	emitAgent(&b, "synthesizer", a.MainModel, 65536, "[]")
	if a.AudioModel != "" {
		emitAgent(&b, "media-reader", a.AudioModel, 32768, "[]")
		b.WriteString("    inputs: [text, image, audio]\n")
	}
	if a.VisionModel != "" {
		emitAgent(&b, "image-reader", a.VisionModel, 32768, "[]")
		b.WriteString("    inputs: [text, image]\n")
	}
	if a.Coding {
		emitCodingAgents(&b, a)
	}
	b.WriteString("\n")

	b.WriteString("tools:\n")
	if a.WebSearch {
		emitTool(&b, "web_search", a.SearchKind, a.SearchURL)
	}
	if a.WebFetch {
		emitTool(&b, "web_fetch", a.FetchKind, a.FetchURL)
	}
	if a.EmbedModel != "" {
		b.WriteString("  stage_memory:\n    store: default_vector\n")
	}
	b.WriteString("\n")

	if a.JudgeModel != "" {
		b.WriteString("gates:\n  rubric_path: config/rubric.md\n  deterministic_checks:\n    max_rounds: 1\n")
		fmt.Fprintf(&b, "  judge:\n    provider: default\n    model: %s\n    max_rounds: 1\n    threshold: 0.6\n\n", a.JudgeModel)
	}

	b.WriteString("dag:\n  max_active_nodes: 2\n\n")
	if a.Coding {
		emitWorkspace(&b, a)
	}
	b.WriteString("server:\n  addr: \":8080\"\n")
	return b.String()
}

// emitCodingAgents renders the three coding agents, mirroring the reference
// config/quack.yaml roster: each is an EXTERNAL agent over ACP (the pi-acp shim
// drives the model bound here), explorer and reviewer read-only. quack has no
// native repo/exec tools - they left the registry with the ACP switch - so
// these agents carry no tools: list at all.
func emitCodingAgents(b *strings.Builder, a InitAnswers) {
	model := a.CoderModel
	if model == "" {
		model = a.MainModel
	}
	acp := func(readOnly bool) {
		b.WriteString("    acp:\n      command: [node, /usr/local/lib/pi-acp/pi-acp.mjs]   # needs node + the pi-acp shim (tools/pi-acp/ in the repo, /usr/local/lib/pi-acp/ in the image)\n")
		if readOnly {
			b.WriteString("      read_only: true\n")
		}
	}
	emitAgent(b, "code-implementer", model, 65536, "")
	b.WriteString("    judge_rounds: 8   # coding converges via the judge+revise grind\n")
	acp(false)
	emitAgent(b, "code-explorer", model, 65536, "")
	b.WriteString("    judge_rounds: 2\n")
	acp(true)
	emitAgent(b, "code-reviewer", model, 65536, "")
	b.WriteString("    judge_rounds: 2\n")
	acp(true)
}

// emitWorkspace renders the workspace section the coding agents need: the
// sandbox mode the ACP child processes run inside (bwrap needs bubblewrap
// installed; none = no OS boundary).
func emitWorkspace(b *strings.Builder, a InitAnswers) {
	sandbox := a.Sandbox
	if sandbox == "" {
		sandbox = "bwrap"
	}
	fmt.Fprintf(b, "workspace:\n  sandbox: %s\n\n", sandbox)
}

// EnvExports is the set of `export` lines the wizard prints so the emitted
// ${ENV} references resolve. Only secrets get env refs (the API key); the
// endpoint and model names are hardcoded into the config, so there's nothing
// to export beyond the key.
func EnvExports(a InitAnswers) []string {
	var out []string
	if a.APIKey != "" {
		out = append(out, fmt.Sprintf("export QUACK_LLM_API_KEY=%q", a.APIKey))
	}
	return out
}

func emitStore(b *strings.Builder, name, kind, url string) {
	if kind == "" {
		kind = "sqlite"
	}
	if url == "" {
		url = DefaultBackendURL(kind)
	}
	fmt.Fprintf(b, "  %s:\n    kind: %s\n    url: %s\n", name, kind, url)
}

func emitTool(b *strings.Builder, name, kind, url string) {
	if kind == "" {
		return
	}
	if url == "" {
		url = DefaultBackendURL(kind)
	}
	if url == "" {
		fmt.Fprintf(b, "  %s:\n    kind: %s\n", name, kind)
		return
	}
	fmt.Fprintf(b, "  %s:\n    kind: %s\n    url: %s\n", name, kind, url)
}

// emitModels renders the models: registry entry for every distinct model
// referenced below - by an agent, gates.judge, or the vector store's
// embedder - each such reference must resolve to a registry entry.
func emitModels(b *strings.Builder, a InitAnswers) {
	coder := a.CoderModel
	if coder == "" {
		coder = a.MainModel
	}
	seen := map[string]bool{}
	b.WriteString("models:\n")
	for _, mr := range []struct{ model, role string }{
		{a.MainModel, "worker"}, {a.AudioModel, "worker"}, {a.VisionModel, "worker"}, {coder, "worker"},
		{a.JudgeModel, "judge"}, {a.EmbedModel, "embed"},
	} {
		if mr.model == "" || seen[mr.model] {
			continue
		}
		seen[mr.model] = true
		fmt.Fprintf(b, "  %s:\n    provider: default\n    role: %s\n", mr.model, mr.role)
	}
	b.WriteString("\n")
}

func emitOrchTools(b *strings.Builder, a InitAnswers) {
	tools := []string{"web_search", "web_fetch", "summarize", "current_date"}
	if a.EmbedModel != "" {
		tools = append(tools, "commit_memory")
	}
	fmt.Fprintf(b, "  tools: [%s]\n", strings.Join(tools, ", "))
}

// emitAgent renders one agent; a blank tools omits the key (ACP agents have none).
func emitAgent(b *strings.Builder, name, model string, ctx int, tools string) {
	fmt.Fprintf(b, "  %s:\n    bundle: agents/%s\n    provider: default\n    model: %s\n    context_window: %d\n",
		name, name, model, ctx)
	if tools != "" {
		fmt.Fprintf(b, "    tools: %s\n", tools)
	}
}

// DefaultBackendURL is the no-docker default connection for a store/tool kind,
// applied when the user leaves the URL blank - and surfaced live as the URL
// field's placeholder in the wizard, so the default tracks the selected kind.
// Kinds that need no URL (exa is API-key based; direct fetches in-process)
// return "".
func DefaultBackendURL(kind string) string {
	switch kind {
	case "sqlite":
		return "quack.db"
	case "qdrant":
		return "localhost:6334"
	case "postgres":
		return "postgres://quack:quack@localhost:5432/quack?sslmode=disable"
	case "searxng":
		return "http://localhost:8080"
	case "crawl4ai":
		return "http://localhost:11235"
	default: // exa, direct - no URL needed
		return ""
	}
}
