package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

// InitAnswers is the `quack server init` wizard's output, kept out of internal/wizard so it's testable
// without a Huh form. Its yaml tags are also the `server init --answers <file>` format.
type InitAnswers struct {
	Endpoint string `yaml:"endpoint"` // LLM endpoint (OpenAI-compatible base URL)
	APIKey   string `yaml:"api_key"`  // typed; emitted as ${QUACK_LLM_API_KEY} (the export is printed)

	MainModel   string `yaml:"main_model"`   // orchestrator + researcher (the common case)
	JudgeModel  string `yaml:"judge_model"`  // blank ⇒ trust gate disabled
	EmbedModel  string `yaml:"embed_model"`  // blank ⇒ semantic memory disabled
	VisionModel string `yaml:"vision_model"` // blank ⇒ no image-reader agent
	AudioModel  string `yaml:"audio_model"`  // blank ⇒ no media-reader agent

	// Stores - each kind picks the adapter; url is the connection (blank ⇒ the
	// emitter fills the no-docker default for that kind).
	SessionKind string `yaml:"session_kind"` // sqlite | postgres
	SessionURL  string `yaml:"session_url"`
	MemoryKind  string `yaml:"memory_kind"` // sqlite | qdrant  (blank when EmbedModel empty)
	MemoryURL   string `yaml:"memory_url"`
	SearchKind  string `yaml:"search_kind"` // exa | searxng   (blank when web search off)
	SearchURL   string `yaml:"search_url"`
	FetchKind   string `yaml:"fetch_kind"` // direct | crawl4ai (blank when web fetch off)
	FetchURL    string `yaml:"fetch_url"`

	WebSearch bool `yaml:"web_search"` // optional-feature toggles (drive which stores are emitted)
	WebFetch  bool `yaml:"web_fetch"`

	// Coding - emit the coding agents (code-implementer/explorer/reviewer) plus
	// the workspace section they need (sandbox + run_command/run_code guards).
	Coding     bool   `yaml:"coding"`
	CoderModel string `yaml:"coder_model"` // blank ⇒ reuse MainModel
	Sandbox    string `yaml:"sandbox"`     // workspace.sandbox: bwrap | none (blank ⇒ bwrap, the server default)
}

// LoadInitAnswersFile applies env prefill first, then the file's values on
// top - an --answers file only has to name what differs from the environment.
func LoadInitAnswersFile(path string) (InitAnswers, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return InitAnswers{}, fmt.Errorf("read --answers %s: %w", path, err)
	}
	a := InitAnswers{WebSearch: true, WebFetch: true}
	PrefillFromEnv(&a)
	if err := yaml.Unmarshal(raw, &a); err != nil {
		return InitAnswers{}, fmt.Errorf("parse --answers %s: %w", path, err)
	}
	return a, nil
}

// WriteServerConfig writes a to outPath and prints the confirmation + env
// exports - the shared tail for both the wizard and a headless --answers init.
func WriteServerConfig(a InitAnswers, outPath string) error {
	if dir := filepath.Dir(outPath); dir != "" && dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("create %s: %w", dir, err)
		}
	}
	if err := os.WriteFile(outPath, []byte(EmitServerConfig(a)), 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Printf("\n✓ Wrote %s\n", outPath)
	for _, line := range envExports(a) {
		fmt.Println(line)
	}
	return nil
}

// EmitServerConfig renders quack.yaml from the answers. Secrets become ${ENV} refs (the caller prints
// the exports); media-reader and image-reader are included only with an audio or vision model.
func EmitServerConfig(a InitAnswers) string {
	var b strings.Builder
	b.WriteString("# Quack configuration - generated by `quack server init`.\n")
	b.WriteString("# The API key is read from ${QUACK_LLM_API_KEY}; set it with the export the wizard prints.\n\n")

	b.WriteString("providers:\n  default:\n    kind: openai\n")
	fmt.Fprintf(&b, "    endpoint: %s\n    api_key: ${QUACK_LLM_API_KEY}\n\n", a.Endpoint)

	b.WriteString("stores:\n")
	emitStore(&b, "default_postgres", a.SessionKind, a.SessionURL)
	if a.EmbedModel != "" {
		emitStore(&b, "default_vector", a.MemoryKind, a.MemoryURL)
	}
	b.WriteString("\n")

	b.WriteString("session:\n  store: default_postgres\n")
	if a.EmbedModel == "" {
		b.WriteString("  # semantic memory is off (no embedding model was selected)\n")
	}
	b.WriteString("\n")

	fmt.Fprintf(&b, "orchestrator:\n  provider: default\n  model: %s\n", a.MainModel)
	emitOrchTools(&b, a)
	b.WriteString("\n")

	emitModels(&b, a)

	b.WriteString("agents:\n")
	researcherTools := baseTools(a)
	if a.EmbedModel != "" {
		researcherTools = append(researcherTools, "stage_memory")
	}
	emitAgent(&b, "web-researcher", a.MainModel, 65536, "["+strings.Join(researcherTools, ", ")+"]")
	emitAgent(&b, "synthesizer", a.MainModel, 65536, "[]")
	if a.AudioModel != "" {
		emitAgent(&b, "media-reader", a.AudioModel, 32768, "[]")
		b.WriteString("    inputs: [text, image, audio]\n")
	}
	if a.VisionModel != "" {
		emitAgent(&b, "image-reader", a.VisionModel, 32768, "[]")
		b.WriteString("    inputs: [text, image]\n")
	}
	if a.Coding {
		emitCodingAgents(&b, a)
	}
	b.WriteString("\n")

	if a.Coding {
		emitCodingPlugins(&b)
	}

	b.WriteString("tools:\n")
	if toolEnabled(a.WebSearch, a.SearchKind) {
		emitTool(&b, "web_search", a.SearchKind, a.SearchURL)
	}
	if toolEnabled(a.WebFetch, a.FetchKind) {
		emitTool(&b, "web_fetch", a.FetchKind, a.FetchURL)
	}
	if a.EmbedModel != "" {
		b.WriteString("  stage_memory:\n    store: default_vector\n")
	}
	b.WriteString("\n")

	if a.JudgeModel != "" {
		b.WriteString("gates:\n  rubric_path: config/rubric.md\n  deterministic_checks:\n    max_rounds: 1\n")
		fmt.Fprintf(&b, "  judge:\n    provider: default\n    model: %s\n    max_rounds: 1\n    threshold: 0.6\n\n", a.JudgeModel)
	}

	b.WriteString("dag:\n  max_active_nodes: 2\n\n")
	if a.Coding {
		emitWorkspace(&b, a)
	}
	b.WriteString("server:\n  addr: \":8080\"\n")
	return b.String()
}

// codingPluginSeed restates the shipped default plugin list plus
// .agents/plugins/github: plugins.seed replaces the default, not extends it.
var codingPluginSeed = []string{
	"github:fagerbergj/dotagents", "github:DietrichGebert/ponytail@v4.9.0",
	".agents/plugins/usage", ".agents/plugins/github",
}

// emitCodingAgents renders the three coding agents as override-only entries -
// bundle/tools/skills come from .agents/plugins/github's agent.yaml.
func emitCodingAgents(b *strings.Builder, a InitAnswers) {
	model := a.CoderModel
	if model == "" {
		model = a.MainModel
	}
	acp := func(readOnly bool) {
		b.WriteString("    acp:\n      command: [node, /usr/local/lib/pi-acp/pi-acp.mjs]   # needs node + the pi-acp shim (tools/pi-acp/ in the repo, /usr/local/lib/pi-acp/ in the image)\n")
		if readOnly {
			b.WriteString("      read_only: true\n")
		}
	}
	emitCodingAgentOverride(b, "code-implementer", model)
	b.WriteString("    judge_rounds: 8   # coding converges via the judge+revise grind\n")
	acp(false)
	emitCodingAgentOverride(b, "code-explorer", model)
	b.WriteString("    judge_rounds: 2\n")
	acp(true)
	emitCodingAgentOverride(b, "code-reviewer", model)
	b.WriteString("    judge_rounds: 2\n")
	acp(true)
}

// emitCodingAgentOverride writes an agents.<name>: header with no bundle: -
// the github plugin supplies it - just the model override and optional: true.
func emitCodingAgentOverride(b *strings.Builder, name, model string) {
	fmt.Fprintf(b, "  %s:\n    provider: default\n    model: %s\n    optional: true\n", name, model)
}

// emitCodingPlugins renders the plugins.seed list Coding needs so
// .agents/plugins/github actually seeds its three agents.
func emitCodingPlugins(b *strings.Builder) {
	b.WriteString("plugins:\n  seed:\n")
	for _, p := range codingPluginSeed {
		fmt.Fprintf(b, "    - %s\n", p)
	}
	b.WriteString("\n")
}

// emitWorkspace renders the sandbox mode ACP child processes run inside
// (bwrap needs bubblewrap installed; none = no OS boundary).
func emitWorkspace(b *strings.Builder, a InitAnswers) {
	sandbox := a.Sandbox
	if sandbox == "" {
		sandbox = "bwrap"
	}
	fmt.Fprintf(b, "workspace:\n  sandbox: %s\n\n", sandbox)
}

// envExports is the `export` lines the wizard prints so the emitted ${ENV} refs resolve;
// only the API key is a secret, everything else is hardcoded.
func envExports(a InitAnswers) []string {
	var out []string
	if a.APIKey != "" {
		out = append(out, fmt.Sprintf("export QUACK_LLM_API_KEY=%q", a.APIKey))
	}
	return out
}

func emitStore(b *strings.Builder, name, kind, url string) {
	if kind == "" {
		kind = "sqlite"
	}
	if url == "" {
		url = DefaultBackendURL(kind)
	}
	fmt.Fprintf(b, "  %s:\n    kind: %s\n    url: %s\n", name, kind, url)
}

func emitTool(b *strings.Builder, name, kind, url string) {
	if kind == "" {
		return
	}
	if url == "" {
		url = DefaultBackendURL(kind)
	}
	if url == "" {
		fmt.Fprintf(b, "  %s:\n    kind: %s\n", name, kind)
		return
	}
	fmt.Fprintf(b, "  %s:\n    kind: %s\n    url: %s\n", name, kind, url)
}

// emitModels renders a models: registry entry for every model an agent, gates.judge,
// or the vector store's embedder references; each reference must resolve.
func emitModels(b *strings.Builder, a InitAnswers) {
	coder := a.CoderModel
	if coder == "" {
		coder = a.MainModel
	}
	seen := map[string]bool{}
	b.WriteString("models:\n")
	for _, mr := range []struct{ model, role string }{
		{a.MainModel, "worker"}, {a.AudioModel, "worker"}, {a.VisionModel, "worker"}, {coder, "worker"},
		{a.JudgeModel, "judge"}, {a.EmbedModel, "embed"},
	} {
		if mr.model == "" || seen[mr.model] {
			continue
		}
		seen[mr.model] = true
		fmt.Fprintf(b, "  %s:\n    provider: default\n    role: %s\n", mr.model, mr.role)
	}
	b.WriteString("\n")
}

// toolEnabled mirrors emitTool's own gate: a toggle with no kind chosen
// emits nothing under `tools:`, so nothing may reference the tool either.
func toolEnabled(toggle bool, kind string) bool {
	return toggle && kind != ""
}

// baseTools is shared by the orchestrator and web-researcher: an agent
// referencing web_search/web_fetch when `tools:` doesn't define it fails at boot.
func baseTools(a InitAnswers) []string {
	var t []string
	if toolEnabled(a.WebSearch, a.SearchKind) {
		t = append(t, "web_search")
	}
	if toolEnabled(a.WebFetch, a.FetchKind) {
		t = append(t, "web_fetch")
	}
	return append(t, "summarize", "current_date")
}

func emitOrchTools(b *strings.Builder, a InitAnswers) {
	tools := baseTools(a)
	if a.EmbedModel != "" {
		tools = append(tools, "commit_memory")
	}
	fmt.Fprintf(b, "  tools: [%s]\n", strings.Join(tools, ", "))
}

// emitAgent renders one agent; a blank tools omits the key (ACP agents have none).
func emitAgent(b *strings.Builder, name, model string, ctx int, tools string) {
	fmt.Fprintf(b, "  %s:\n    bundle: agents/%s\n    provider: default\n    model: %s\n    context_window: %d\n",
		name, name, model, ctx)
	if tools != "" {
		fmt.Fprintf(b, "    tools: %s\n", tools)
	}
}

// DefaultBackendURL is the no-docker default URL for a store/tool kind, also shown as the wizard
// field's placeholder. Kinds needing no URL (exa, direct fetch) return "".
func DefaultBackendURL(kind string) string {
	switch kind {
	case "sqlite":
		return "quack.db"
	case "qdrant":
		return "localhost:6334"
	case "postgres":
		return "postgres://quack:quack@localhost:5432/quack?sslmode=disable"
	case "searxng":
		return "http://localhost:8080"
	case "crawl4ai":
		return "http://localhost:11235"
	default: // exa, direct - no URL needed
		return ""
	}
}
