// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package schema

import (
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AgentActivityOutputItemType.
const (
	QuackActivity AgentActivityOutputItemType = "quack:activity"
)

// Valid indicates whether the value is a known member of the AgentActivityOutputItemType enum.
func (e AgentActivityOutputItemType) Valid() bool {
	switch e {
	case QuackActivity:
		return true
	default:
		return false
	}
}

// Defines values for ChatStatus.
const (
	ChatStatusFailed     ChatStatus = "failed"
	ChatStatusIdle       ChatStatus = "idle"
	ChatStatusNeedsInput ChatStatus = "needs_input"
	ChatStatusRunning    ChatStatus = "running"
)

// Valid indicates whether the value is a known member of the ChatStatus enum.
func (e ChatStatus) Valid() bool {
	switch e {
	case ChatStatusFailed:
		return true
	case ChatStatusIdle:
		return true
	case ChatStatusNeedsInput:
		return true
	case ChatStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for DagOutputItemType.
const (
	QuackDag DagOutputItemType = "quack:dag"
)

// Valid indicates whether the value is a known member of the DagOutputItemType enum.
func (e DagOutputItemType) Valid() bool {
	switch e {
	case QuackDag:
		return true
	default:
		return false
	}
}

// Defines values for ItemStatus.
const (
	Completed  ItemStatus = "completed"
	InProgress ItemStatus = "in_progress"
	Incomplete ItemStatus = "incomplete"
)

// Valid indicates whether the value is a known member of the ItemStatus enum.
func (e ItemStatus) Valid() bool {
	switch e {
	case Completed:
		return true
	case InProgress:
		return true
	case Incomplete:
		return true
	default:
		return false
	}
}

// Defines values for MessageOutputItemType.
const (
	Message MessageOutputItemType = "message"
)

// Valid indicates whether the value is a known member of the MessageOutputItemType enum.
func (e MessageOutputItemType) Valid() bool {
	switch e {
	case Message:
		return true
	default:
		return false
	}
}

// Defines values for NodeStatus.
const (
	NodeStatusCancelled  NodeStatus = "cancelled"
	NodeStatusDone       NodeStatus = "done"
	NodeStatusFailed     NodeStatus = "failed"
	NodeStatusNeedsInput NodeStatus = "needs_input"
	NodeStatusQueued     NodeStatus = "queued"
	NodeStatusRunning    NodeStatus = "running"
)

// Valid indicates whether the value is a known member of the NodeStatus enum.
func (e NodeStatus) Valid() bool {
	switch e {
	case NodeStatusCancelled:
		return true
	case NodeStatusDone:
		return true
	case NodeStatusFailed:
		return true
	case NodeStatusNeedsInput:
		return true
	case NodeStatusQueued:
		return true
	case NodeStatusRunning:
		return true
	default:
		return false
	}
}

// Defines values for OutputTextPartType.
const (
	OutputText OutputTextPartType = "output_text"
)

// Valid indicates whether the value is a known member of the OutputTextPartType enum.
func (e OutputTextPartType) Valid() bool {
	switch e {
	case OutputText:
		return true
	default:
		return false
	}
}

// Defines values for ReasoningPartType.
const (
	Reasoning ReasoningPartType = "reasoning"
)

// Valid indicates whether the value is a known member of the ReasoningPartType enum.
func (e ReasoningPartType) Valid() bool {
	switch e {
	case Reasoning:
		return true
	default:
		return false
	}
}

// Defines values for ResponseStatus.
const (
	Cancelled ResponseStatus = "cancelled"
)

// Valid indicates whether the value is a known member of the ResponseStatus enum.
func (e ResponseStatus) Valid() bool {
	switch e {
	case Cancelled:
		return true
	default:
		return false
	}
}

// Defines values for TurnInputRole.
const (
	User TurnInputRole = "user"
)

// Valid indicates whether the value is a known member of the TurnInputRole enum.
func (e TurnInputRole) Valid() bool {
	switch e {
	case User:
		return true
	default:
		return false
	}
}

// AgentActivityOutputItem defines model for AgentActivityOutputItem.
type AgentActivityOutputItem struct {
	Id        string                      `json:"id"`
	Status    ItemStatus                  `json:"status"`
	ToolCalls []ToolCallItem              `json:"tool_calls"`
	Type      AgentActivityOutputItemType `json:"type"`
}

// AgentActivityOutputItemType defines model for AgentActivityOutputItem.Type.
type AgentActivityOutputItemType string

// Capabilities A discovery document (in the spirit of an OIDC discovery document or a SCIM ServiceProviderConfig) describing which optional extensions this server has configured. Each capability is its own object rather than a bare boolean so it can grow fields later without changing shape.
type Capabilities struct {
	// Github The GitHub App extension (internal/github) — repo-linked chats, webhook dispatch, PR/issue delivery.
	Github GitHubCapability `json:"github"`
}

// ChatDetail defines model for ChatDetail.
type ChatDetail struct {
	CreatedAt time.Time `json:"created_at"`

	// GithubRepo `<owner>/<repo>` of the originating GitHub issue/PR, present only for GitHub-originated chats.
	GithubRepo *string `json:"github_repo,omitempty"`

	// GithubUrl Web URL of the originating GitHub issue/PR, present only for GitHub-originated chats.
	GithubUrl *string `json:"github_url,omitempty"`
	Id        string  `json:"id"`

	// PendingQuestion The unanswered question blocking the chat, present only when status is `needs_input`.
	PendingQuestion *string `json:"pending_question,omitempty"`

	// Status A chat's derived state: `running` while a turn is actively streaming, `needs_input` when the last turn paused on an unanswered question (a mid-node ask, a guarded operation awaiting approve/deny — the workspace.guards confirm tier — or a top-level clarification), `failed` when the last turn's DAG has a failed node and no answer text followed, else `idle`.
	Status       ChatStatus `json:"status"`
	SystemPrompt string     `json:"system_prompt"`
	Title        *string    `json:"title,omitempty"`
	Turns        []Turn     `json:"turns"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

// ChatList defines model for ChatList.
type ChatList struct {
	Data []ChatSummary `json:"data"`
}

// ChatStatus A chat's derived state: `running` while a turn is actively streaming, `needs_input` when the last turn paused on an unanswered question (a mid-node ask, a guarded operation awaiting approve/deny — the workspace.guards confirm tier — or a top-level clarification), `failed` when the last turn's DAG has a failed node and no answer text followed, else `idle`.
type ChatStatus string

// ChatSummary defines model for ChatSummary.
type ChatSummary struct {
	CreatedAt time.Time `json:"created_at"`

	// GithubRepo `<owner>/<repo>` of the originating GitHub issue/PR, present only for GitHub-originated chats.
	GithubRepo *string `json:"github_repo,omitempty"`

	// GithubUrl Web URL of the originating GitHub issue/PR, present only for GitHub-originated chats.
	GithubUrl *string `json:"github_url,omitempty"`
	Id        string  `json:"id"`

	// PendingQuestion The unanswered question blocking the chat, present only when status is `needs_input`.
	PendingQuestion *string `json:"pending_question,omitempty"`

	// Status A chat's derived state: `running` while a turn is actively streaming, `needs_input` when the last turn paused on an unanswered question (a mid-node ask, a guarded operation awaiting approve/deny — the workspace.guards confirm tier — or a top-level clarification), `failed` when the last turn's DAG has a failed node and no answer text followed, else `idle`.
	Status       ChatStatus `json:"status"`
	SystemPrompt string     `json:"system_prompt"`
	Title        *string    `json:"title,omitempty"`
	UpdatedAt    time.Time  `json:"updated_at"`
}

// ContentPart defines model for ContentPart.
type ContentPart struct {
	union json.RawMessage
}

// CreateChatBody defines model for CreateChatBody.
type CreateChatBody struct {
	SystemPrompt *string `json:"system_prompt,omitempty"`
}

// DagEdge defines model for DagEdge.
type DagEdge struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// DagNodeDef defines model for DagNodeDef.
type DagNodeDef struct {
	Agent     string   `json:"agent"`
	DependsOn []string `json:"depends_on"`
	Id        string   `json:"id"`
	Task      string   `json:"task"`
}

// DagNodeState defines model for DagNodeState.
type DagNodeState struct {
	CompletionTokens *int     `json:"completion_tokens,omitempty"`
	Error            *string  `json:"error,omitempty"`
	FinishReason     *string  `json:"finish_reason,omitempty"`
	FinishedAtMs     *int     `json:"finished_at_ms,omitempty"`
	JudgeFinalScore  *float64 `json:"judge_final_score,omitempty"`
	JudgePassed      *bool    `json:"judge_passed,omitempty"`
	JudgeRounds      *int     `json:"judge_rounds,omitempty"`
	Model            *string  `json:"model,omitempty"`
	OutputPreview    *string  `json:"output_preview,omitempty"`
	PromptTokens     *int     `json:"prompt_tokens,omitempty"`
	ReasoningTokens  *int     `json:"reasoning_tokens,omitempty"`
	ServerDurationMs *int     `json:"server_duration_ms,omitempty"`
	StartedAtMs      *int     `json:"started_at_ms,omitempty"`

	// Status A DAG node's canonical lifecycle state. Legal transitions (enforced
	// server-side by internal/dag.CanTransition):
	//   queued      → running, cancelled, failed (stale-on-restart)
	//   running     → running (steer, in place), needs_input, done, failed, cancelled
	//   needs_input → running (resumed), cancelled
	//   done        → queued (retry)
	//   failed      → queued (retry)
	//   cancelled   → queued (retry)
	Status      NodeStatus `json:"status"`
	TotalTokens *int       `json:"total_tokens,omitempty"`
}

// DagOutputItem defines model for DagOutputItem.
type DagOutputItem struct {
	Edges      []DagEdge               `json:"edges"`
	Id         string                  `json:"id"`
	NodeStates map[string]DagNodeState `json:"node_states"`
	Nodes      []DagNodeDef            `json:"nodes"`
	PlanId     string                  `json:"plan_id"`
	Status     ItemStatus              `json:"status"`
	Type       DagOutputItemType       `json:"type"`
}

// DagOutputItemType defines model for DagOutputItem.Type.
type DagOutputItemType string

// GitHubCapability The GitHub App extension (internal/github) — repo-linked chats, webhook dispatch, PR/issue delivery.
type GitHubCapability struct {
	Enabled bool `json:"enabled"`
}

// ItemStatus defines model for ItemStatus.
type ItemStatus string

// MessageOutputItem defines model for MessageOutputItem.
type MessageOutputItem struct {
	Content []ContentPart         `json:"content"`
	Id      string                `json:"id"`
	Status  ItemStatus            `json:"status"`
	Type    MessageOutputItemType `json:"type"`
}

// MessageOutputItemType defines model for MessageOutputItem.Type.
type MessageOutputItemType string

// NodeStatus A DAG node's canonical lifecycle state. Legal transitions (enforced
// server-side by internal/dag.CanTransition):
//
//	queued      → running, cancelled, failed (stale-on-restart)
//	running     → running (steer, in place), needs_input, done, failed, cancelled
//	needs_input → running (resumed), cancelled
//	done        → queued (retry)
//	failed      → queued (retry)
//	cancelled   → queued (retry)
type NodeStatus string

// NodeStatusUpdateBody defines model for NodeStatusUpdateBody.
type NodeStatusUpdateBody struct {
	// Guidance Required when status is "running" (steer); optional and folded into the node's task when status is "queued" (retry). Unused for "cancelled".
	Guidance *string `json:"guidance,omitempty"`

	// Status A DAG node's canonical lifecycle state. Legal transitions (enforced
	// server-side by internal/dag.CanTransition):
	//   queued      → running, cancelled, failed (stale-on-restart)
	//   running     → running (steer, in place), needs_input, done, failed, cancelled
	//   needs_input → running (resumed), cancelled
	//   done        → queued (retry)
	//   failed      → queued (retry)
	//   cancelled   → queued (retry)
	Status NodeStatus `json:"status"`
}

// OutputItem defines model for OutputItem.
type OutputItem struct {
	union json.RawMessage
}

// OutputTextPart defines model for OutputTextPart.
type OutputTextPart struct {
	Text string             `json:"text"`
	Type OutputTextPartType `json:"type"`
}

// OutputTextPartType defines model for OutputTextPart.Type.
type OutputTextPartType string

// ReasoningPart defines model for ReasoningPart.
type ReasoningPart struct {
	Text string            `json:"text"`
	Type ReasoningPartType `json:"type"`
}

// ReasoningPartType defines model for ReasoningPart.Type.
type ReasoningPartType string

// ResponseStatus The only supported target status for a response — cancelling the active run. (A separate enum from NodeStatus, which has states with no meaning at the response/run level.)
type ResponseStatus string

// ResponseStatusUpdateBody defines model for ResponseStatusUpdateBody.
type ResponseStatusUpdateBody struct {
	// Status The only supported target status for a response — cancelling the active run. (A separate enum from NodeStatus, which has states with no meaning at the response/run level.)
	Status ResponseStatus `json:"status"`
}

// SendMessageBody defines model for SendMessageBody.
type SendMessageBody struct {
	Content string `json:"content"`
}

// ToolCallItem defines model for ToolCallItem.
type ToolCallItem struct {
	Args   *map[string]interface{} `json:"args,omitempty"`
	CallId string                  `json:"call_id"`
	Name   string                  `json:"name"`
	Result *map[string]interface{} `json:"result,omitempty"`
}

// TransitionError defines model for TransitionError.
type TransitionError struct {
	Allowed []NodeStatus `json:"allowed"`

	// Current A DAG node's canonical lifecycle state. Legal transitions (enforced
	// server-side by internal/dag.CanTransition):
	//   queued      → running, cancelled, failed (stale-on-restart)
	//   running     → running (steer, in place), needs_input, done, failed, cancelled
	//   needs_input → running (resumed), cancelled
	//   done        → queued (retry)
	//   failed      → queued (retry)
	//   cancelled   → queued (retry)
	Current NodeStatus `json:"current"`
	Error   string     `json:"error"`
}

// Turn defines model for Turn.
type Turn struct {
	CreatedAt time.Time `json:"created_at"`
	Id        string    `json:"id"`
	Input     TurnInput `json:"input"`

	// Model Model that produced the orchestrator's own reply this turn. Absent for DAG turns (their models are per-node in DagNodeState).
	Model  *string      `json:"model,omitempty"`
	Output []OutputItem `json:"output"`
	Usage  *Usage       `json:"usage,omitempty"`
}

// TurnInput defines model for TurnInput.
type TurnInput struct {
	Content string        `json:"content"`
	Role    TurnInputRole `json:"role"`
}

// TurnInputRole defines model for TurnInput.Role.
type TurnInputRole string

// Usage defines model for Usage.
type Usage struct {
	InputTokens  *int `json:"input_tokens,omitempty"`
	OutputTokens *int `json:"output_tokens,omitempty"`
}

// ChatID defines model for ChatID.
type ChatID = string

// NodeID defines model for NodeID.
type NodeID = string

// ResponseID defines model for ResponseID.
type ResponseID = string

// CreateChatJSONRequestBody defines body for CreateChat for application/json ContentType.
type CreateChatJSONRequestBody = CreateChatBody

// UpdateNodeStatusJSONRequestBody defines body for UpdateNodeStatus for application/json ContentType.
type UpdateNodeStatusJSONRequestBody = NodeStatusUpdateBody

// SendChatMessageJSONRequestBody defines body for SendChatMessage for application/json ContentType.
type SendChatMessageJSONRequestBody = SendMessageBody

// UpdateResponseStatusJSONRequestBody defines body for UpdateResponseStatus for application/json ContentType.
type UpdateResponseStatusJSONRequestBody = ResponseStatusUpdateBody

// AsOutputTextPart returns the union data inside the ContentPart as a OutputTextPart
func (t ContentPart) AsOutputTextPart() (OutputTextPart, error) {
	var body OutputTextPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromOutputTextPart overwrites any union data inside the ContentPart as the provided OutputTextPart
func (t *ContentPart) FromOutputTextPart(v OutputTextPart) error {
	v.Type = "output_text"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeOutputTextPart performs a merge with any union data inside the ContentPart, using the provided OutputTextPart
func (t *ContentPart) MergeOutputTextPart(v OutputTextPart) error {
	v.Type = "output_text"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsReasoningPart returns the union data inside the ContentPart as a ReasoningPart
func (t ContentPart) AsReasoningPart() (ReasoningPart, error) {
	var body ReasoningPart
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromReasoningPart overwrites any union data inside the ContentPart as the provided ReasoningPart
func (t *ContentPart) FromReasoningPart(v ReasoningPart) error {
	v.Type = "reasoning"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeReasoningPart performs a merge with any union data inside the ContentPart, using the provided ReasoningPart
func (t *ContentPart) MergeReasoningPart(v ReasoningPart) error {
	v.Type = "reasoning"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ContentPart) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t ContentPart) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "output_text":
		return t.AsOutputTextPart()
	case "reasoning":
		return t.AsReasoningPart()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ContentPart) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ContentPart) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsMessageOutputItem returns the union data inside the OutputItem as a MessageOutputItem
func (t OutputItem) AsMessageOutputItem() (MessageOutputItem, error) {
	var body MessageOutputItem
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromMessageOutputItem overwrites any union data inside the OutputItem as the provided MessageOutputItem
func (t *OutputItem) FromMessageOutputItem(v MessageOutputItem) error {
	v.Type = "message"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeMessageOutputItem performs a merge with any union data inside the OutputItem, using the provided MessageOutputItem
func (t *OutputItem) MergeMessageOutputItem(v MessageOutputItem) error {
	v.Type = "message"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsDagOutputItem returns the union data inside the OutputItem as a DagOutputItem
func (t OutputItem) AsDagOutputItem() (DagOutputItem, error) {
	var body DagOutputItem
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromDagOutputItem overwrites any union data inside the OutputItem as the provided DagOutputItem
func (t *OutputItem) FromDagOutputItem(v DagOutputItem) error {
	v.Type = "quack:dag"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeDagOutputItem performs a merge with any union data inside the OutputItem, using the provided DagOutputItem
func (t *OutputItem) MergeDagOutputItem(v DagOutputItem) error {
	v.Type = "quack:dag"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsAgentActivityOutputItem returns the union data inside the OutputItem as a AgentActivityOutputItem
func (t OutputItem) AsAgentActivityOutputItem() (AgentActivityOutputItem, error) {
	var body AgentActivityOutputItem
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromAgentActivityOutputItem overwrites any union data inside the OutputItem as the provided AgentActivityOutputItem
func (t *OutputItem) FromAgentActivityOutputItem(v AgentActivityOutputItem) error {
	v.Type = "quack:activity"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeAgentActivityOutputItem performs a merge with any union data inside the OutputItem, using the provided AgentActivityOutputItem
func (t *OutputItem) MergeAgentActivityOutputItem(v AgentActivityOutputItem) error {
	v.Type = "quack:activity"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t OutputItem) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t OutputItem) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "message":
		return t.AsMessageOutputItem()
	case "quack:activity":
		return t.AsAgentActivityOutputItem()
	case "quack:dag":
		return t.AsDagOutputItem()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t OutputItem) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *OutputItem) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Which optional extensions are enabled
	// (GET /api/v1/capabilities)
	GetCapabilities(w http.ResponseWriter, r *http.Request)
	// List chats
	// (GET /api/v1/chats)
	ListChats(w http.ResponseWriter, r *http.Request)
	// Create a chat
	// (POST /api/v1/chats)
	CreateChat(w http.ResponseWriter, r *http.Request)
	// Delete a chat
	// (DELETE /api/v1/chats/{chat_id})
	DeleteChat(w http.ResponseWriter, r *http.Request, chatId ChatID)
	// Get a chat with its turns
	// (GET /api/v1/chats/{chat_id})
	GetChat(w http.ResponseWriter, r *http.Request, chatId ChatID)
	// Transition a DAG node's status (cancel, retry, or steer)
	// (PUT /api/v1/chats/{chat_id}/nodes/{node_id}/status)
	UpdateNodeStatus(w http.ResponseWriter, r *http.Request, chatId ChatID, nodeId NodeID)
	// Send a message and stream the response
	// (POST /api/v1/chats/{chat_id}/responses)
	SendChatMessage(w http.ResponseWriter, r *http.Request, chatId ChatID)
	// Get a specific response (turn) with its output items
	// (GET /api/v1/chats/{chat_id}/responses/{response_id})
	GetResponse(w http.ResponseWriter, r *http.Request, chatId ChatID, responseId ResponseID)
	// Cancel the chat's active run by response id
	// (PUT /api/v1/chats/{chat_id}/responses/{response_id}/status)
	UpdateResponseStatus(w http.ResponseWriter, r *http.Request, chatId ChatID, responseId ResponseID)
	// Subscribe to a chat's live response stream
	// (GET /api/v1/chats/{chat_id}/stream)
	SubscribeChatStream(w http.ResponseWriter, r *http.Request, chatId ChatID)
	// Liveness check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Which optional extensions are enabled
// (GET /api/v1/capabilities)
func (_ Unimplemented) GetCapabilities(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List chats
// (GET /api/v1/chats)
func (_ Unimplemented) ListChats(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a chat
// (POST /api/v1/chats)
func (_ Unimplemented) CreateChat(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a chat
// (DELETE /api/v1/chats/{chat_id})
func (_ Unimplemented) DeleteChat(w http.ResponseWriter, r *http.Request, chatId ChatID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a chat with its turns
// (GET /api/v1/chats/{chat_id})
func (_ Unimplemented) GetChat(w http.ResponseWriter, r *http.Request, chatId ChatID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Transition a DAG node's status (cancel, retry, or steer)
// (PUT /api/v1/chats/{chat_id}/nodes/{node_id}/status)
func (_ Unimplemented) UpdateNodeStatus(w http.ResponseWriter, r *http.Request, chatId ChatID, nodeId NodeID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send a message and stream the response
// (POST /api/v1/chats/{chat_id}/responses)
func (_ Unimplemented) SendChatMessage(w http.ResponseWriter, r *http.Request, chatId ChatID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a specific response (turn) with its output items
// (GET /api/v1/chats/{chat_id}/responses/{response_id})
func (_ Unimplemented) GetResponse(w http.ResponseWriter, r *http.Request, chatId ChatID, responseId ResponseID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cancel the chat's active run by response id
// (PUT /api/v1/chats/{chat_id}/responses/{response_id}/status)
func (_ Unimplemented) UpdateResponseStatus(w http.ResponseWriter, r *http.Request, chatId ChatID, responseId ResponseID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Subscribe to a chat's live response stream
// (GET /api/v1/chats/{chat_id}/stream)
func (_ Unimplemented) SubscribeChatStream(w http.ResponseWriter, r *http.Request, chatId ChatID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness check
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCapabilities operation middleware
func (siw *ServerInterfaceWrapper) GetCapabilities(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCapabilities(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListChats operation middleware
func (siw *ServerInterfaceWrapper) ListChats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChat operation middleware
func (siw *ServerInterfaceWrapper) CreateChat(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChat(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChat operation middleware
func (siw *ServerInterfaceWrapper) DeleteChat(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chat_id" -------------
	var chatId ChatID

	err = runtime.BindStyledParameterWithOptions("simple", "chat_id", chi.URLParam(r, "chat_id"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chat_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChat(w, r, chatId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChat operation middleware
func (siw *ServerInterfaceWrapper) GetChat(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chat_id" -------------
	var chatId ChatID

	err = runtime.BindStyledParameterWithOptions("simple", "chat_id", chi.URLParam(r, "chat_id"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chat_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChat(w, r, chatId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNodeStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateNodeStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chat_id" -------------
	var chatId ChatID

	err = runtime.BindStyledParameterWithOptions("simple", "chat_id", chi.URLParam(r, "chat_id"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chat_id", Err: err})
		return
	}

	// ------------- Path parameter "node_id" -------------
	var nodeId NodeID

	err = runtime.BindStyledParameterWithOptions("simple", "node_id", chi.URLParam(r, "node_id"), &nodeId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "node_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNodeStatus(w, r, chatId, nodeId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendChatMessage operation middleware
func (siw *ServerInterfaceWrapper) SendChatMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chat_id" -------------
	var chatId ChatID

	err = runtime.BindStyledParameterWithOptions("simple", "chat_id", chi.URLParam(r, "chat_id"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chat_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendChatMessage(w, r, chatId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetResponse operation middleware
func (siw *ServerInterfaceWrapper) GetResponse(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chat_id" -------------
	var chatId ChatID

	err = runtime.BindStyledParameterWithOptions("simple", "chat_id", chi.URLParam(r, "chat_id"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chat_id", Err: err})
		return
	}

	// ------------- Path parameter "response_id" -------------
	var responseId ResponseID

	err = runtime.BindStyledParameterWithOptions("simple", "response_id", chi.URLParam(r, "response_id"), &responseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "response_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetResponse(w, r, chatId, responseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateResponseStatus operation middleware
func (siw *ServerInterfaceWrapper) UpdateResponseStatus(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chat_id" -------------
	var chatId ChatID

	err = runtime.BindStyledParameterWithOptions("simple", "chat_id", chi.URLParam(r, "chat_id"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chat_id", Err: err})
		return
	}

	// ------------- Path parameter "response_id" -------------
	var responseId ResponseID

	err = runtime.BindStyledParameterWithOptions("simple", "response_id", chi.URLParam(r, "response_id"), &responseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "response_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateResponseStatus(w, r, chatId, responseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SubscribeChatStream operation middleware
func (siw *ServerInterfaceWrapper) SubscribeChatStream(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chat_id" -------------
	var chatId ChatID

	err = runtime.BindStyledParameterWithOptions("simple", "chat_id", chi.URLParam(r, "chat_id"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chat_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubscribeChatStream(w, r, chatId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/capabilities", wrapper.GetCapabilities)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/chats", wrapper.ListChats)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/chats", wrapper.CreateChat)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/chats/{chat_id}", wrapper.DeleteChat)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/chats/{chat_id}", wrapper.GetChat)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/chats/{chat_id}/nodes/{node_id}/status", wrapper.UpdateNodeStatus)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/chats/{chat_id}/responses", wrapper.SendChatMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/chats/{chat_id}/responses/{response_id}", wrapper.GetResponse)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/api/v1/chats/{chat_id}/responses/{response_id}/status", wrapper.UpdateResponseStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/chats/{chat_id}/stream", wrapper.SubscribeChatStream)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})

	return r
}
