// Package schema provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package schema

import (
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ChatMessageRole.
const (
	Assistant ChatMessageRole = "assistant"
	User      ChatMessageRole = "user"
)

// Valid indicates whether the value is a known member of the ChatMessageRole enum.
func (e ChatMessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case User:
		return true
	default:
		return false
	}
}

// ChatDetail defines model for ChatDetail.
type ChatDetail struct {
	CreatedAt    time.Time     `json:"created_at"`
	Id           string        `json:"id"`
	Messages     []ChatMessage `json:"messages"`
	SystemPrompt string        `json:"system_prompt"`
	UpdatedAt    time.Time     `json:"updated_at"`
}

// ChatList defines model for ChatList.
type ChatList struct {
	Data []ChatSummary `json:"data"`
}

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	Content string          `json:"content"`
	Role    ChatMessageRole `json:"role"`
}

// ChatMessageRole defines model for ChatMessage.Role.
type ChatMessageRole string

// ChatSummary defines model for ChatSummary.
type ChatSummary struct {
	CreatedAt    time.Time `json:"created_at"`
	Id           string    `json:"id"`
	Title        string    `json:"title,omitempty"`
	SystemPrompt string    `json:"system_prompt"`
	UpdatedAt    time.Time `json:"updated_at"`
}

// CreateChatBody defines model for CreateChatBody.
type CreateChatBody struct {
	SystemPrompt *string `json:"system_prompt,omitempty"`
}

// SendMessageBody defines model for SendMessageBody.
type SendMessageBody struct {
	Content string `json:"content"`
}

// ChatID defines model for ChatID.
type ChatID = string

// CreateChatJSONRequestBody defines body for CreateChat for application/json ContentType.
type CreateChatJSONRequestBody = CreateChatBody

// SendChatMessageJSONRequestBody defines body for SendChatMessage for application/json ContentType.
type SendChatMessageJSONRequestBody = SendMessageBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List chats
	// (GET /api/v1/chats)
	ListChats(w http.ResponseWriter, r *http.Request)
	// Create a chat
	// (POST /api/v1/chats)
	CreateChat(w http.ResponseWriter, r *http.Request)
	// Delete a chat
	// (DELETE /api/v1/chats/{chat_id})
	DeleteChat(w http.ResponseWriter, r *http.Request, chatId ChatID)
	// Get a chat with its messages
	// (GET /api/v1/chats/{chat_id})
	GetChat(w http.ResponseWriter, r *http.Request, chatId ChatID)
	// Send a message and stream the response
	// (POST /api/v1/chats/{chat_id}/messages)
	SendChatMessage(w http.ResponseWriter, r *http.Request, chatId ChatID)
	// Liveness check
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List chats
// (GET /api/v1/chats)
func (_ Unimplemented) ListChats(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a chat
// (POST /api/v1/chats)
func (_ Unimplemented) CreateChat(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete a chat
// (DELETE /api/v1/chats/{chat_id})
func (_ Unimplemented) DeleteChat(w http.ResponseWriter, r *http.Request, chatId ChatID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a chat with its messages
// (GET /api/v1/chats/{chat_id})
func (_ Unimplemented) GetChat(w http.ResponseWriter, r *http.Request, chatId ChatID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Send a message and stream the response
// (POST /api/v1/chats/{chat_id}/messages)
func (_ Unimplemented) SendChatMessage(w http.ResponseWriter, r *http.Request, chatId ChatID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness check
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListChats operation middleware
func (siw *ServerInterfaceWrapper) ListChats(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListChats(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateChat operation middleware
func (siw *ServerInterfaceWrapper) CreateChat(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateChat(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteChat operation middleware
func (siw *ServerInterfaceWrapper) DeleteChat(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chat_id" -------------
	var chatId ChatID

	err = runtime.BindStyledParameterWithOptions("simple", "chat_id", chi.URLParam(r, "chat_id"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chat_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteChat(w, r, chatId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetChat operation middleware
func (siw *ServerInterfaceWrapper) GetChat(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chat_id" -------------
	var chatId ChatID

	err = runtime.BindStyledParameterWithOptions("simple", "chat_id", chi.URLParam(r, "chat_id"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chat_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetChat(w, r, chatId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendChatMessage operation middleware
func (siw *ServerInterfaceWrapper) SendChatMessage(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "chat_id" -------------
	var chatId ChatID

	err = runtime.BindStyledParameterWithOptions("simple", "chat_id", chi.URLParam(r, "chat_id"), &chatId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "chat_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendChatMessage(w, r, chatId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/chats", wrapper.ListChats)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/chats", wrapper.CreateChat)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/chats/{chat_id}", wrapper.DeleteChat)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/chats/{chat_id}", wrapper.GetChat)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/chats/{chat_id}/messages", wrapper.SendChatMessage)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})

	return r
}
