// Package langfusegen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package langfusegen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes basicAuthContextKey = "BasicAuth.Scopes"
)

// Defines values for DatasetItemMediaReferenceField.
const (
	ExpectedOutput DatasetItemMediaReferenceField = "expectedOutput"
	Input          DatasetItemMediaReferenceField = "input"
	Metadata       DatasetItemMediaReferenceField = "metadata"
)

// Valid indicates whether the value is a known member of the DatasetItemMediaReferenceField enum.
func (e DatasetItemMediaReferenceField) Valid() bool {
	switch e {
	case ExpectedOutput:
		return true
	case Input:
		return true
	case Metadata:
		return true
	default:
		return false
	}
}

// Defines values for DatasetStatus.
const (
	ACTIVE   DatasetStatus = "ACTIVE"
	ARCHIVED DatasetStatus = "ARCHIVED"
)

// Valid indicates whether the value is a known member of the DatasetStatus enum.
func (e DatasetStatus) Valid() bool {
	switch e {
	case ACTIVE:
		return true
	case ARCHIVED:
		return true
	default:
		return false
	}
}

// CreateDatasetItemRequest defines model for CreateDatasetItemRequest.
type CreateDatasetItemRequest struct {
	DatasetName    string      `json:"datasetName"`
	ExpectedOutput interface{} `json:"expectedOutput,omitempty"`

	// Id Dataset items are upserted on their id. Id needs to be unique (project-level), cannot be reused across datasets, and must be at most 255 characters.
	Id                  *string        `json:"id,omitempty"`
	Input               interface{}    `json:"input,omitempty"`
	Metadata            interface{}    `json:"metadata,omitempty"`
	SourceObservationId *string        `json:"sourceObservationId,omitempty"`
	SourceTraceId       *string        `json:"sourceTraceId,omitempty"`
	Status              *DatasetStatus `json:"status,omitempty"`
}

// CreateDatasetRequest defines model for CreateDatasetRequest.
type CreateDatasetRequest struct {
	Description *string `json:"description,omitempty"`

	// ExpectedOutputSchema JSON Schema for validating dataset item expected outputs. When set, all new and existing dataset items will be validated against this schema.
	ExpectedOutputSchema interface{} `json:"expectedOutputSchema,omitempty"`

	// InputSchema JSON Schema for validating dataset item inputs. When set, all new and existing dataset items will be validated against this schema.
	InputSchema interface{} `json:"inputSchema,omitempty"`
	Metadata    interface{} `json:"metadata,omitempty"`
	Name        string      `json:"name"`
}

// CreateDatasetRunItemRequest defines model for CreateDatasetRunItemRequest.
type CreateDatasetRunItemRequest struct {
	// CreatedAt Optional timestamp to set the createdAt field of the dataset run item. If not provided or null, defaults to current timestamp.
	CreatedAt     *time.Time `json:"createdAt,omitempty"`
	DatasetItemId string     `json:"datasetItemId"`

	// DatasetVersion ISO 8601 timestamp (RFC 3339, Section 5.6) in UTC (e.g., "2026-01-21T14:35:42Z").
	// Specifies the dataset version to use for this experiment run.
	// If provided, the experiment will use dataset items as they existed at or before this timestamp.
	// If not provided, uses the latest version of dataset items.
	DatasetVersion *time.Time `json:"datasetVersion,omitempty"`

	// Metadata Metadata of the dataset run, updates run if run already exists
	Metadata      interface{} `json:"metadata,omitempty"`
	ObservationId *string     `json:"observationId,omitempty"`

	// RunDescription Description of the run. If run exists, description will be updated.
	RunDescription *string `json:"runDescription,omitempty"`
	RunName        string  `json:"runName"`

	// TraceId traceId should always be provided. For compatibility with older SDK versions it can also be inferred from the provided observationId.
	TraceId *string `json:"traceId,omitempty"`
}

// Dataset defines model for Dataset.
type Dataset struct {
	CreatedAt time.Time `json:"createdAt"`

	// Description Description of the dataset
	Description *string `json:"description"`

	// ExpectedOutputSchema JSON Schema for validating dataset item expected outputs
	ExpectedOutputSchema interface{} `json:"expectedOutputSchema"`
	Id                   string      `json:"id"`

	// InputSchema JSON Schema for validating dataset item inputs
	InputSchema interface{} `json:"inputSchema"`

	// Metadata Metadata associated with the dataset
	Metadata  interface{} `json:"metadata"`
	Name      string      `json:"name"`
	ProjectId string      `json:"projectId"`
	UpdatedAt time.Time   `json:"updatedAt"`
}

// DatasetItem defines model for DatasetItem.
type DatasetItem struct {
	CreatedAt   time.Time `json:"createdAt"`
	DatasetId   string    `json:"datasetId"`
	DatasetName string    `json:"datasetName"`

	// ExpectedOutput Expected output for the dataset item
	ExpectedOutput interface{} `json:"expectedOutput"`
	Id             string      `json:"id"`

	// Input Input data for the dataset item
	Input interface{} `json:"input"`

	// MediaReferences Resolved Langfuse media references found in input, expectedOutput, and metadata.
	MediaReferences []DatasetItemMediaReference `json:"mediaReferences"`

	// Metadata Metadata associated with the dataset item
	Metadata interface{} `json:"metadata"`

	// SourceObservationId The observation ID that sourced this dataset item
	SourceObservationId *string `json:"sourceObservationId"`

	// SourceTraceId The trace ID that sourced this dataset item
	SourceTraceId *string       `json:"sourceTraceId"`
	Status        DatasetStatus `json:"status"`
	UpdatedAt     time.Time     `json:"updatedAt"`
}

// DatasetItemMediaReference defines model for DatasetItemMediaReference.
type DatasetItemMediaReference struct {
	Field DatasetItemMediaReferenceField `json:"field"`

	// JsonPath JSONPath of the string holding the reference within the field, e.g. `$['image']`
	JsonPath string                         `json:"jsonPath"`
	Media    DatasetItemMediaReferenceMedia `json:"media"`

	// ReferenceString The Langfuse media reference string, e.g. `@@@langfuseMedia:type=image/png|id=...|source=bytes@@@`
	ReferenceString string `json:"referenceString"`
}

// DatasetItemMediaReferenceField defines model for DatasetItemMediaReferenceField.
type DatasetItemMediaReferenceField string

// DatasetItemMediaReferenceMedia defines model for DatasetItemMediaReferenceMedia.
type DatasetItemMediaReferenceMedia struct {
	// ContentLength The size of the media record in bytes
	ContentLength int `json:"contentLength"`

	// ContentType The MIME type of the media record
	ContentType string `json:"contentType"`

	// MediaId The unique langfuse identifier of the media record
	MediaId string `json:"mediaId"`

	// Url The signed download URL of the media record
	Url string `json:"url"`

	// UrlExpiry The expiry date and time of the download URL
	UrlExpiry string `json:"urlExpiry"`
}

// DatasetRun defines model for DatasetRun.
type DatasetRun struct {
	// CreatedAt The date and time when the dataset run was created
	CreatedAt time.Time `json:"createdAt"`

	// DatasetId Id of the associated dataset
	DatasetId string `json:"datasetId"`

	// DatasetName Name of the associated dataset
	DatasetName string `json:"datasetName"`

	// Description Description of the run
	Description *string `json:"description"`

	// Id Unique identifier of the dataset run
	Id string `json:"id"`

	// Metadata Metadata of the dataset run
	Metadata interface{} `json:"metadata"`

	// Name Name of the dataset run
	Name string `json:"name"`

	// UpdatedAt The date and time when the dataset run was last updated
	UpdatedAt time.Time `json:"updatedAt"`
}

// DatasetRunItem defines model for DatasetRunItem.
type DatasetRunItem struct {
	CreatedAt      time.Time `json:"createdAt"`
	DatasetItemId  string    `json:"datasetItemId"`
	DatasetRunId   string    `json:"datasetRunId"`
	DatasetRunName string    `json:"datasetRunName"`
	Id             string    `json:"id"`

	// ObservationId The observation ID associated with this run item
	ObservationId *string   `json:"observationId"`
	TraceId       string    `json:"traceId"`
	UpdatedAt     time.Time `json:"updatedAt"`
}

// DatasetRunWithItems defines model for DatasetRunWithItems.
type DatasetRunWithItems = DatasetRun

// DatasetStatus defines model for DatasetStatus.
type DatasetStatus string

// DeleteDatasetItemResponse defines model for DeleteDatasetItemResponse.
type DeleteDatasetItemResponse struct {
	// Message Success message after deletion
	Message string `json:"message"`
}

// DeleteDatasetRunResponse defines model for DeleteDatasetRunResponse.
type DeleteDatasetRunResponse struct {
	Message string `json:"message"`
}

// Deprecation Migration signal returned by deprecated endpoints. Optional fields are omitted when they have no value.
type Deprecation struct {
	// DocsUrl Link to the migration documentation (markdown), when available.
	DocsUrl *string `json:"docsUrl,omitempty"`

	// Message Human- and agent-readable summary of the deprecation and its replacement.
	Message string `json:"message"`

	// Replacement The replacement endpoint, e.g. "GET /api/public/v2/observations". Omitted when the endpoint is being removed without a direct replacement.
	Replacement *string `json:"replacement,omitempty"`

	// SunsetAt ISO date after which the endpoint may stop working, when a removal date is committed.
	SunsetAt *string `json:"sunsetAt,omitempty"`
}

// PaginatedDatasetItems defines model for PaginatedDatasetItems.
type PaginatedDatasetItems struct {
	Data []DatasetItem     `json:"data"`
	Meta UtilsMetaResponse `json:"meta"`
}

// PaginatedDatasetRunItems defines model for PaginatedDatasetRunItems.
type PaginatedDatasetRunItems struct {
	// UnderscoreDeprecation Migration signal returned by deprecated endpoints. Optional fields are omitted when they have no value.
	UnderscoreDeprecation *Deprecation      `json:"_deprecation,omitempty"`
	Data                  []DatasetRunItem  `json:"data"`
	Meta                  UtilsMetaResponse `json:"meta"`
}

// PaginatedDatasetRuns defines model for PaginatedDatasetRuns.
type PaginatedDatasetRuns struct {
	// UnderscoreDeprecation Migration signal returned by deprecated endpoints. Optional fields are omitted when they have no value.
	UnderscoreDeprecation *Deprecation      `json:"_deprecation,omitempty"`
	Data                  []DatasetRun      `json:"data"`
	Meta                  UtilsMetaResponse `json:"meta"`
}

// PaginatedDatasets defines model for PaginatedDatasets.
type PaginatedDatasets struct {
	Data []Dataset         `json:"data"`
	Meta UtilsMetaResponse `json:"meta"`
}

// UtilsMetaResponse defines model for utilsMetaResponse.
type UtilsMetaResponse struct {
	// Limit number of items per page
	Limit int `json:"limit"`

	// Page current page number
	Page int `json:"page"`

	// TotalItems number of total items given the current filters/selection (if any)
	TotalItems int `json:"totalItems"`

	// TotalPages number of total pages given the current limit
	TotalPages int `json:"totalPages"`
}

// basicAuthContextKey is the context key for BasicAuth security scheme
type basicAuthContextKey string

// DatasetItemsListParams defines parameters for DatasetItemsList.
type DatasetItemsListParams struct {
	DatasetName         *string `form:"datasetName,omitempty" json:"datasetName,omitempty"`
	SourceTraceId       *string `form:"sourceTraceId,omitempty" json:"sourceTraceId,omitempty"`
	SourceObservationId *string `form:"sourceObservationId,omitempty" json:"sourceObservationId,omitempty"`

	// Version ISO 8601 timestamp (RFC 3339, Section 5.6) in UTC (e.g., "2026-01-21T14:35:42Z").
	// If provided, returns state of dataset at this timestamp.
	// If not provided, returns the latest version. Requires datasetName to be specified.
	Version *time.Time `form:"version,omitempty" json:"version,omitempty"`

	// Page page number, starts at 1
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit limit of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DatasetRunItemsListParams defines parameters for DatasetRunItemsList.
type DatasetRunItemsListParams struct {
	DatasetId string `form:"datasetId" json:"datasetId"`
	RunName   string `form:"runName" json:"runName"`

	// Page page number, starts at 1
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit limit of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DatasetsGetRunsParams defines parameters for DatasetsGetRuns.
type DatasetsGetRunsParams struct {
	// Page page number, starts at 1
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit limit of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DatasetsListParams defines parameters for DatasetsList.
type DatasetsListParams struct {
	// Page page number, starts at 1
	Page *int `form:"page,omitempty" json:"page,omitempty"`

	// Limit limit of items per page
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// DatasetItemsCreateJSONRequestBody defines body for DatasetItemsCreate for application/json ContentType.
type DatasetItemsCreateJSONRequestBody = CreateDatasetItemRequest

// DatasetRunItemsCreateJSONRequestBody defines body for DatasetRunItemsCreate for application/json ContentType.
type DatasetRunItemsCreateJSONRequestBody = CreateDatasetRunItemRequest

// DatasetsCreateJSONRequestBody defines body for DatasetsCreate for application/json ContentType.
type DatasetsCreateJSONRequestBody = CreateDatasetRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// DatasetItemsList request
	DatasetItemsList(ctx context.Context, params *DatasetItemsListParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatasetItemsCreateWithBody request with any body
	DatasetItemsCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DatasetItemsCreate(ctx context.Context, body DatasetItemsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatasetItemsDelete request
	DatasetItemsDelete(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatasetItemsGet request
	DatasetItemsGet(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatasetRunItemsList request
	DatasetRunItemsList(ctx context.Context, params *DatasetRunItemsListParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatasetRunItemsCreateWithBody request with any body
	DatasetRunItemsCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DatasetRunItemsCreate(ctx context.Context, body DatasetRunItemsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatasetsGetRuns request
	DatasetsGetRuns(ctx context.Context, datasetName string, params *DatasetsGetRunsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatasetsDeleteRun request
	DatasetsDeleteRun(ctx context.Context, datasetName string, runName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatasetsGetRun request
	DatasetsGetRun(ctx context.Context, datasetName string, runName string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatasetsList request
	DatasetsList(ctx context.Context, params *DatasetsListParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatasetsCreateWithBody request with any body
	DatasetsCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	DatasetsCreate(ctx context.Context, body DatasetsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DatasetsGet request
	DatasetsGet(ctx context.Context, datasetName string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) DatasetItemsList(ctx context.Context, params *DatasetItemsListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetItemsListRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetItemsCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetItemsCreateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetItemsCreate(ctx context.Context, body DatasetItemsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetItemsCreateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetItemsDelete(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetItemsDeleteRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetItemsGet(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetItemsGetRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetRunItemsList(ctx context.Context, params *DatasetRunItemsListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetRunItemsListRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetRunItemsCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetRunItemsCreateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetRunItemsCreate(ctx context.Context, body DatasetRunItemsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetRunItemsCreateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetsGetRuns(ctx context.Context, datasetName string, params *DatasetsGetRunsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetsGetRunsRequest(c.Server, datasetName, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetsDeleteRun(ctx context.Context, datasetName string, runName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetsDeleteRunRequest(c.Server, datasetName, runName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetsGetRun(ctx context.Context, datasetName string, runName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetsGetRunRequest(c.Server, datasetName, runName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetsList(ctx context.Context, params *DatasetsListParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetsListRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetsCreateWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetsCreateRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetsCreate(ctx context.Context, body DatasetsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetsCreateRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DatasetsGet(ctx context.Context, datasetName string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDatasetsGetRequest(c.Server, datasetName)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewDatasetItemsListRequest generates requests for DatasetItemsList
func NewDatasetItemsListRequest(server string, params *DatasetItemsListParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public/dataset-items")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.DatasetName != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "datasetName", *params.DatasetName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SourceTraceId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sourceTraceId", *params.SourceTraceId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.SourceObservationId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sourceObservationId", *params.SourceObservationId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Version != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "version", *params.Version, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: "date-time"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDatasetItemsCreateRequest calls the generic DatasetItemsCreate builder with application/json body
func NewDatasetItemsCreateRequest(server string, body DatasetItemsCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDatasetItemsCreateRequestWithBody(server, "application/json", bodyReader)
}

// NewDatasetItemsCreateRequestWithBody generates requests for DatasetItemsCreate with any type of body
func NewDatasetItemsCreateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public/dataset-items")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDatasetItemsDeleteRequest generates requests for DatasetItemsDelete
func NewDatasetItemsDeleteRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public/dataset-items/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDatasetItemsGetRequest generates requests for DatasetItemsGet
func NewDatasetItemsGetRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public/dataset-items/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDatasetRunItemsListRequest generates requests for DatasetRunItemsList
func NewDatasetRunItemsListRequest(server string, params *DatasetRunItemsListParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public/dataset-run-items")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "datasetId", params.DatasetId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if queryFrag, err := runtime.StyleParamWithOptions("form", true, "runName", params.RunName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
			return nil, err
		} else {
			for _, qp := range strings.Split(queryFrag, "&") {
				rawQueryFragments = append(rawQueryFragments, qp)
			}
		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDatasetRunItemsCreateRequest calls the generic DatasetRunItemsCreate builder with application/json body
func NewDatasetRunItemsCreateRequest(server string, body DatasetRunItemsCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDatasetRunItemsCreateRequestWithBody(server, "application/json", bodyReader)
}

// NewDatasetRunItemsCreateRequestWithBody generates requests for DatasetRunItemsCreate with any type of body
func NewDatasetRunItemsCreateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public/dataset-run-items")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDatasetsGetRunsRequest generates requests for DatasetsGetRuns
func NewDatasetsGetRunsRequest(server string, datasetName string, params *DatasetsGetRunsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "datasetName", datasetName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public/datasets/%s/runs", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDatasetsDeleteRunRequest generates requests for DatasetsDeleteRun
func NewDatasetsDeleteRunRequest(server string, datasetName string, runName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "datasetName", datasetName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "runName", runName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public/datasets/%s/runs/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodDelete, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDatasetsGetRunRequest generates requests for DatasetsGetRun
func NewDatasetsGetRunRequest(server string, datasetName string, runName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "datasetName", datasetName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "runName", runName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public/datasets/%s/runs/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDatasetsListRequest generates requests for DatasetsList
func NewDatasetsListRequest(server string, params *DatasetsListParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public/v2/datasets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "limit", *params.Limit, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewDatasetsCreateRequest calls the generic DatasetsCreate builder with application/json body
func NewDatasetsCreateRequest(server string, body DatasetsCreateJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewDatasetsCreateRequestWithBody(server, "application/json", bodyReader)
}

// NewDatasetsCreateRequestWithBody generates requests for DatasetsCreate with any type of body
func NewDatasetsCreateRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public/v2/datasets")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDatasetsGetRequest generates requests for DatasetsGet
func NewDatasetsGetRequest(server string, datasetName string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "datasetName", datasetName, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/public/v2/datasets/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// DatasetItemsListWithResponse request
	DatasetItemsListWithResponse(ctx context.Context, params *DatasetItemsListParams, reqEditors ...RequestEditorFn) (*DatasetItemsListResponse, error)

	// DatasetItemsCreateWithBodyWithResponse request with any body
	DatasetItemsCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DatasetItemsCreateResponse, error)

	DatasetItemsCreateWithResponse(ctx context.Context, body DatasetItemsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*DatasetItemsCreateResponse, error)

	// DatasetItemsDeleteWithResponse request
	DatasetItemsDeleteWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DatasetItemsDeleteResponse, error)

	// DatasetItemsGetWithResponse request
	DatasetItemsGetWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DatasetItemsGetResponse, error)

	// DatasetRunItemsListWithResponse request
	DatasetRunItemsListWithResponse(ctx context.Context, params *DatasetRunItemsListParams, reqEditors ...RequestEditorFn) (*DatasetRunItemsListResponse, error)

	// DatasetRunItemsCreateWithBodyWithResponse request with any body
	DatasetRunItemsCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DatasetRunItemsCreateResponse, error)

	DatasetRunItemsCreateWithResponse(ctx context.Context, body DatasetRunItemsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*DatasetRunItemsCreateResponse, error)

	// DatasetsGetRunsWithResponse request
	DatasetsGetRunsWithResponse(ctx context.Context, datasetName string, params *DatasetsGetRunsParams, reqEditors ...RequestEditorFn) (*DatasetsGetRunsResponse, error)

	// DatasetsDeleteRunWithResponse request
	DatasetsDeleteRunWithResponse(ctx context.Context, datasetName string, runName string, reqEditors ...RequestEditorFn) (*DatasetsDeleteRunResponse, error)

	// DatasetsGetRunWithResponse request
	DatasetsGetRunWithResponse(ctx context.Context, datasetName string, runName string, reqEditors ...RequestEditorFn) (*DatasetsGetRunResponse, error)

	// DatasetsListWithResponse request
	DatasetsListWithResponse(ctx context.Context, params *DatasetsListParams, reqEditors ...RequestEditorFn) (*DatasetsListResponse, error)

	// DatasetsCreateWithBodyWithResponse request with any body
	DatasetsCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DatasetsCreateResponse, error)

	DatasetsCreateWithResponse(ctx context.Context, body DatasetsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*DatasetsCreateResponse, error)

	// DatasetsGetWithResponse request
	DatasetsGetWithResponse(ctx context.Context, datasetName string, reqEditors ...RequestEditorFn) (*DatasetsGetResponse, error)
}

type DatasetItemsListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PaginatedDatasetItems
	JSON400      *interface{}
	JSON401      *interface{}
	JSON403      *interface{}
	JSON404      *interface{}
	JSON405      *interface{}
}

// Status returns HTTPResponse.Status
func (r DatasetItemsListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatasetItemsListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatasetItemsListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatasetItemsCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DatasetItem
	JSON400      *interface{}
	JSON401      *interface{}
	JSON403      *interface{}
	JSON404      *interface{}
	JSON405      *interface{}
}

// Status returns HTTPResponse.Status
func (r DatasetItemsCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatasetItemsCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatasetItemsCreateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatasetItemsDeleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeleteDatasetItemResponse
	JSON400      *interface{}
	JSON401      *interface{}
	JSON403      *interface{}
	JSON404      *interface{}
	JSON405      *interface{}
}

// Status returns HTTPResponse.Status
func (r DatasetItemsDeleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatasetItemsDeleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatasetItemsDeleteResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatasetItemsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DatasetItem
	JSON400      *interface{}
	JSON401      *interface{}
	JSON403      *interface{}
	JSON404      *interface{}
	JSON405      *interface{}
}

// Status returns HTTPResponse.Status
func (r DatasetItemsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatasetItemsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatasetItemsGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatasetRunItemsListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PaginatedDatasetRunItems
	JSON400      *interface{}
	JSON401      *interface{}
	JSON403      *interface{}
	JSON404      *interface{}
	JSON405      *interface{}
}

// Status returns HTTPResponse.Status
func (r DatasetRunItemsListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatasetRunItemsListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatasetRunItemsListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatasetRunItemsCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DatasetRunItem
	JSON400      *interface{}
	JSON401      *interface{}
	JSON403      *interface{}
	JSON404      *interface{}
	JSON405      *interface{}
}

// Status returns HTTPResponse.Status
func (r DatasetRunItemsCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatasetRunItemsCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatasetRunItemsCreateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatasetsGetRunsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PaginatedDatasetRuns
	JSON400      *interface{}
	JSON401      *interface{}
	JSON403      *interface{}
	JSON404      *interface{}
	JSON405      *interface{}
}

// Status returns HTTPResponse.Status
func (r DatasetsGetRunsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatasetsGetRunsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatasetsGetRunsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatasetsDeleteRunResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeleteDatasetRunResponse
	JSON400      *interface{}
	JSON401      *interface{}
	JSON403      *interface{}
	JSON404      *interface{}
	JSON405      *interface{}
}

// Status returns HTTPResponse.Status
func (r DatasetsDeleteRunResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatasetsDeleteRunResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatasetsDeleteRunResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatasetsGetRunResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DatasetRunWithItems
	JSON400      *interface{}
	JSON401      *interface{}
	JSON403      *interface{}
	JSON404      *interface{}
	JSON405      *interface{}
}

// Status returns HTTPResponse.Status
func (r DatasetsGetRunResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatasetsGetRunResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatasetsGetRunResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatasetsListResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PaginatedDatasets
	JSON400      *interface{}
	JSON401      *interface{}
	JSON403      *interface{}
	JSON404      *interface{}
	JSON405      *interface{}
}

// Status returns HTTPResponse.Status
func (r DatasetsListResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatasetsListResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatasetsListResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatasetsCreateResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Dataset
	JSON400      *interface{}
	JSON401      *interface{}
	JSON403      *interface{}
	JSON404      *interface{}
	JSON405      *interface{}
}

// Status returns HTTPResponse.Status
func (r DatasetsCreateResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatasetsCreateResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatasetsCreateResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type DatasetsGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Dataset
	JSON400      *interface{}
	JSON401      *interface{}
	JSON403      *interface{}
	JSON404      *interface{}
	JSON405      *interface{}
}

// Status returns HTTPResponse.Status
func (r DatasetsGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DatasetsGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r DatasetsGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// DatasetItemsListWithResponse request returning *DatasetItemsListResponse
func (c *ClientWithResponses) DatasetItemsListWithResponse(ctx context.Context, params *DatasetItemsListParams, reqEditors ...RequestEditorFn) (*DatasetItemsListResponse, error) {
	rsp, err := c.DatasetItemsList(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetItemsListResponse(rsp)
}

// DatasetItemsCreateWithBodyWithResponse request with arbitrary body returning *DatasetItemsCreateResponse
func (c *ClientWithResponses) DatasetItemsCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DatasetItemsCreateResponse, error) {
	rsp, err := c.DatasetItemsCreateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetItemsCreateResponse(rsp)
}

func (c *ClientWithResponses) DatasetItemsCreateWithResponse(ctx context.Context, body DatasetItemsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*DatasetItemsCreateResponse, error) {
	rsp, err := c.DatasetItemsCreate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetItemsCreateResponse(rsp)
}

// DatasetItemsDeleteWithResponse request returning *DatasetItemsDeleteResponse
func (c *ClientWithResponses) DatasetItemsDeleteWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DatasetItemsDeleteResponse, error) {
	rsp, err := c.DatasetItemsDelete(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetItemsDeleteResponse(rsp)
}

// DatasetItemsGetWithResponse request returning *DatasetItemsGetResponse
func (c *ClientWithResponses) DatasetItemsGetWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DatasetItemsGetResponse, error) {
	rsp, err := c.DatasetItemsGet(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetItemsGetResponse(rsp)
}

// DatasetRunItemsListWithResponse request returning *DatasetRunItemsListResponse
func (c *ClientWithResponses) DatasetRunItemsListWithResponse(ctx context.Context, params *DatasetRunItemsListParams, reqEditors ...RequestEditorFn) (*DatasetRunItemsListResponse, error) {
	rsp, err := c.DatasetRunItemsList(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetRunItemsListResponse(rsp)
}

// DatasetRunItemsCreateWithBodyWithResponse request with arbitrary body returning *DatasetRunItemsCreateResponse
func (c *ClientWithResponses) DatasetRunItemsCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DatasetRunItemsCreateResponse, error) {
	rsp, err := c.DatasetRunItemsCreateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetRunItemsCreateResponse(rsp)
}

func (c *ClientWithResponses) DatasetRunItemsCreateWithResponse(ctx context.Context, body DatasetRunItemsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*DatasetRunItemsCreateResponse, error) {
	rsp, err := c.DatasetRunItemsCreate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetRunItemsCreateResponse(rsp)
}

// DatasetsGetRunsWithResponse request returning *DatasetsGetRunsResponse
func (c *ClientWithResponses) DatasetsGetRunsWithResponse(ctx context.Context, datasetName string, params *DatasetsGetRunsParams, reqEditors ...RequestEditorFn) (*DatasetsGetRunsResponse, error) {
	rsp, err := c.DatasetsGetRuns(ctx, datasetName, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetsGetRunsResponse(rsp)
}

// DatasetsDeleteRunWithResponse request returning *DatasetsDeleteRunResponse
func (c *ClientWithResponses) DatasetsDeleteRunWithResponse(ctx context.Context, datasetName string, runName string, reqEditors ...RequestEditorFn) (*DatasetsDeleteRunResponse, error) {
	rsp, err := c.DatasetsDeleteRun(ctx, datasetName, runName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetsDeleteRunResponse(rsp)
}

// DatasetsGetRunWithResponse request returning *DatasetsGetRunResponse
func (c *ClientWithResponses) DatasetsGetRunWithResponse(ctx context.Context, datasetName string, runName string, reqEditors ...RequestEditorFn) (*DatasetsGetRunResponse, error) {
	rsp, err := c.DatasetsGetRun(ctx, datasetName, runName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetsGetRunResponse(rsp)
}

// DatasetsListWithResponse request returning *DatasetsListResponse
func (c *ClientWithResponses) DatasetsListWithResponse(ctx context.Context, params *DatasetsListParams, reqEditors ...RequestEditorFn) (*DatasetsListResponse, error) {
	rsp, err := c.DatasetsList(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetsListResponse(rsp)
}

// DatasetsCreateWithBodyWithResponse request with arbitrary body returning *DatasetsCreateResponse
func (c *ClientWithResponses) DatasetsCreateWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*DatasetsCreateResponse, error) {
	rsp, err := c.DatasetsCreateWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetsCreateResponse(rsp)
}

func (c *ClientWithResponses) DatasetsCreateWithResponse(ctx context.Context, body DatasetsCreateJSONRequestBody, reqEditors ...RequestEditorFn) (*DatasetsCreateResponse, error) {
	rsp, err := c.DatasetsCreate(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetsCreateResponse(rsp)
}

// DatasetsGetWithResponse request returning *DatasetsGetResponse
func (c *ClientWithResponses) DatasetsGetWithResponse(ctx context.Context, datasetName string, reqEditors ...RequestEditorFn) (*DatasetsGetResponse, error) {
	rsp, err := c.DatasetsGet(ctx, datasetName, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDatasetsGetResponse(rsp)
}

// ParseDatasetItemsListResponse parses an HTTP response from a DatasetItemsListWithResponse call
func ParseDatasetItemsListResponse(rsp *http.Response) (*DatasetItemsListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatasetItemsListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PaginatedDatasetItems
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	}

	return response, nil
}

// ParseDatasetItemsCreateResponse parses an HTTP response from a DatasetItemsCreateWithResponse call
func ParseDatasetItemsCreateResponse(rsp *http.Response) (*DatasetItemsCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatasetItemsCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DatasetItem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	}

	return response, nil
}

// ParseDatasetItemsDeleteResponse parses an HTTP response from a DatasetItemsDeleteWithResponse call
func ParseDatasetItemsDeleteResponse(rsp *http.Response) (*DatasetItemsDeleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatasetItemsDeleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeleteDatasetItemResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	}

	return response, nil
}

// ParseDatasetItemsGetResponse parses an HTTP response from a DatasetItemsGetWithResponse call
func ParseDatasetItemsGetResponse(rsp *http.Response) (*DatasetItemsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatasetItemsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DatasetItem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	}

	return response, nil
}

// ParseDatasetRunItemsListResponse parses an HTTP response from a DatasetRunItemsListWithResponse call
func ParseDatasetRunItemsListResponse(rsp *http.Response) (*DatasetRunItemsListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatasetRunItemsListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PaginatedDatasetRunItems
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	}

	return response, nil
}

// ParseDatasetRunItemsCreateResponse parses an HTTP response from a DatasetRunItemsCreateWithResponse call
func ParseDatasetRunItemsCreateResponse(rsp *http.Response) (*DatasetRunItemsCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatasetRunItemsCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DatasetRunItem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	}

	return response, nil
}

// ParseDatasetsGetRunsResponse parses an HTTP response from a DatasetsGetRunsWithResponse call
func ParseDatasetsGetRunsResponse(rsp *http.Response) (*DatasetsGetRunsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatasetsGetRunsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PaginatedDatasetRuns
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	}

	return response, nil
}

// ParseDatasetsDeleteRunResponse parses an HTTP response from a DatasetsDeleteRunWithResponse call
func ParseDatasetsDeleteRunResponse(rsp *http.Response) (*DatasetsDeleteRunResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatasetsDeleteRunResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeleteDatasetRunResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	}

	return response, nil
}

// ParseDatasetsGetRunResponse parses an HTTP response from a DatasetsGetRunWithResponse call
func ParseDatasetsGetRunResponse(rsp *http.Response) (*DatasetsGetRunResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatasetsGetRunResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DatasetRunWithItems
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	}

	return response, nil
}

// ParseDatasetsListResponse parses an HTTP response from a DatasetsListWithResponse call
func ParseDatasetsListResponse(rsp *http.Response) (*DatasetsListResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatasetsListResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PaginatedDatasets
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	}

	return response, nil
}

// ParseDatasetsCreateResponse parses an HTTP response from a DatasetsCreateWithResponse call
func ParseDatasetsCreateResponse(rsp *http.Response) (*DatasetsCreateResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatasetsCreateResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Dataset
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	}

	return response, nil
}

// ParseDatasetsGetResponse parses an HTTP response from a DatasetsGetWithResponse call
func ParseDatasetsGetResponse(rsp *http.Response) (*DatasetsGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DatasetsGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Dataset
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 405:
		var dest interface{}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON405 = &dest

	}

	return response, nil
}
