// Code generated by oapi-codegen. DO NOT EDIT.

package schema

import (
	"encoding/json"
	"net/http"
)

// HealthCheck defines model for healthCheck.
func HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("ok"))
}

// SendChatMessageRequestBody defines model for SendChatMessage.RequestBody.
type SendChatMessageRequestBody struct {
	Content string `json:"content"`
}

// SendMessageBody defines model for SendMessageBody.
type SendMessageBody struct {
	Content string `json:"content"`
}

// ChatSummary defines model for ChatSummary.
type ChatSummary struct {
	ID           string  `json:"id"`
	SystemPrompt *string `json:"system_prompt,omitempty"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
}

// ChatDetail defines model for ChatDetail.
type ChatDetail struct {
	ID           string  `json:"id"`
	SystemPrompt *string `json:"system_prompt,omitempty"`
	CreatedAt    string  `json:"created_at"`
	UpdatedAt    string  `json:"updated_at"`
	Messages     []ChatMessage `json:"messages"`
}

// ChatMessage defines model for ChatMessage.
type ChatMessage struct {
	ID        string `json:"id"`
	Role      string `json:"role"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
	ExternalID *string `json:"external_id,omitempty"`
}

// PaginatedChats defines model for PaginatedChats.
type PaginatedChats struct {
	Data          []ChatSummary `json:"data"`
	NextPageToken *string       `json:"next_page_token,omitempty"`
}

// CreateChatBody defines model for CreateChatBody.
type CreateChatBody struct {
	SystemPrompt *string `json:"system_prompt,omitempty"`
}

// PatchChatBody defines model for PatchChatBody.
type PatchChatBody struct {
	Title        *string `json:"title,omitempty"`
	SystemPrompt *string `json:"system_prompt,omitempty"`
	RagRetrieval *struct {
		Enabled      *bool   `json:"enabled,omitempty"`
		MaxSources   *int    `json:"max_sources,omitempty"`
		MinimumScore *float64 `json:"minimum_score,omitempty"`
	} `json:"rag_retrieval,omitempty"`
}
